<?php

return [
    'roles' => [
        'super-admin', 'administrator', 'content-manager', 'course-manager',
        'publication-manager', 'book-manager', 'order-manager', 'support-manager', 'customer',
    ],
    'admin_roles' => [
        'super-admin', 'administrator', 'content-manager', 'course-manager',
        'publication-manager', 'book-manager', 'order-manager', 'support-manager',
    ],
    'protected_roles' => ['super-admin', 'customer'],
    'permissions' => [
        'admin.dashboard.access',
        'admin-users.view', 'admin-users.create', 'admin-users.update',
        'admin-users.activate', 'admin-users.suspend',
        'roles.view', 'roles.create', 'roles.update', 'roles.assign',
        'permissions.view', 'permissions.assign',
        'engineering-disciplines.view', 'engineering-disciplines.create', 'engineering-disciplines.update', 'engineering-disciplines.delete', 'engineering-disciplines.reorder',
        'categories.view', 'categories.create', 'categories.update', 'categories.delete', 'categories.reorder',
        'topics.view', 'topics.create', 'topics.update', 'topics.delete', 'topics.reorder',
        'tags.view', 'tags.create', 'tags.update', 'tags.delete',
        'course-levels.view', 'course-levels.create', 'course-levels.update', 'course-levels.delete',
        'resource-types.view', 'resource-types.create', 'resource-types.update', 'resource-types.delete',
        'publication-types.view', 'publication-types.create', 'publication-types.update', 'publication-types.delete',
        'pages.view', 'pages.create', 'pages.update', 'pages.delete', 'pages.publish',
        'banners.view', 'banners.create', 'banners.update', 'banners.delete', 'banners.reorder',
        'media.view', 'media.upload', 'media.update', 'media.delete',
        'settings.view', 'settings.update', 'seo.view', 'seo.update',
        'social-links.view', 'social-links.create', 'social-links.update', 'social-links.delete', 'social-links.reorder',
        'redirects.view', 'redirects.create', 'redirects.update', 'redirects.delete',
        'contributors.view', 'contributors.create', 'contributors.update', 'contributors.delete', 'contributors.publish', 'contributors.feature', 'contributors.reorder',
        'articles.view', 'articles.create', 'articles.update', 'articles.delete', 'articles.publish', 'articles.feature', 'courses.view', 'courses.create', 'courses.update', 'courses.delete', 'courses.publish', 'courses.feature', 'courses.curriculum.manage', 'courses.faculty.manage', 'courses.faq.manage', 'publications.view', 'publications.create', 'publications.update', 'publications.delete', 'publications.publish', 'publications.feature', 'publications.preview.manage', 'publications.contributors.manage', 'resources.view', 'resources.create', 'resources.update', 'resources.delete', 'resources.publish', 'resources.feature', 'resources.file.manage', 'resources.preview.manage', 'entitlements.view', 'entitlements.grant', 'entitlements.revoke', 'downloads.view',
        'books.view', 'books.create', 'books.update', 'books.delete', 'books.publish', 'books.feature', 'books.images.manage', 'authors.view', 'authors.create', 'authors.update', 'authors.delete', 'publishers.view', 'publishers.create', 'publishers.update', 'publishers.delete',
        'inventory.view', 'inventory.adjust', 'inventory.increase', 'inventory.decrease', 'inventory.threshold.update', 'inventory.movements.view',
        'coupons.view', 'coupons.create', 'coupons.update', 'coupons.delete', 'coupons.activate', 'coupon-usages.view',
        'shipping.view', 'shipping.settings.view', 'shipping.settings.update', 'shipping.providers.view', 'shipping.providers.configure', 'shipping.providers.toggle', 'shipping.providers.test', 'shipping.rates.view', 'shipping.serviceability.view',
        'orders.view', 'orders.update-status', 'orders.cancel', 'orders.customer.view', 'order-status-history.view',
        'payment-settings.view', 'payment-settings.update', 'payment-providers.view', 'payment-providers.configure', 'payment-providers.toggle', 'payment-providers.test', 'payment-providers.default', 'payment-attempts.view', 'payment-transactions.view', 'payment-reconciliation.run', 'refunds.view',
        'invoice-settings.view', 'invoice-settings.update', 'invoices.view', 'invoices.issue', 'invoices.download', 'invoices.regenerate', 'invoices.void',
        'shipments.view', 'shipments.create', 'shipments.update', 'shipments.cancel', 'shipments.awb.assign', 'shipments.pickup.schedule', 'shipments.label.generate', 'shipments.label.download', 'shipments.manifest.generate', 'shipments.manifest.download', 'shipments.tracking.refresh', 'shipments.reconcile', 'shipment-attempts.view', 'shipment-events.view', 'shipping-webhooks.view',
        'notifications.view', 'notifications.settings.view', 'notifications.settings.update', 'notifications.email.test', 'notifications.logs.view', 'notifications.logs.retry', 'notifications.templates.view', 'notifications.templates.update',
        'enquiries.view', 'enquiries.manage', 'support-tickets.view', 'support-tickets.manage', 'workshops.view', 'workshops.manage', 'careers.view', 'careers.manage',
        'notices.view', 'notices.create', 'notices.update', 'notices.delete', 'notices.publish', 'notices.feature', 'notices.pin', 'gallery.view', 'gallery.create', 'gallery.update', 'gallery.delete', 'gallery.publish', 'gallery.feature', 'gallery.images.manage', 'gallery.images.reorder', 'videos.view', 'videos.create', 'videos.update', 'videos.delete', 'videos.publish', 'videos.feature',
    ],
    'role_permissions' => [
        'super-admin' => ['*'],
        'administrator' => [
            'admin.dashboard.access', 'admin-users.view', 'admin-users.create',
            'admin-users.update', 'admin-users.activate', 'admin-users.suspend',
            'roles.view', 'roles.assign', 'permissions.view',
            'engineering-disciplines.view', 'engineering-disciplines.create', 'engineering-disciplines.update', 'engineering-disciplines.reorder',
            'categories.view', 'categories.create', 'categories.update', 'categories.reorder',
            'topics.view', 'topics.create', 'topics.update', 'topics.reorder',
            'tags.view', 'tags.create', 'tags.update',
            'course-levels.view', 'course-levels.create', 'course-levels.update',
            'resource-types.view', 'resource-types.create', 'resource-types.update',
            'publication-types.view', 'publication-types.create', 'publication-types.update',
            'pages.view', 'pages.create', 'pages.update', 'pages.delete', 'pages.publish',
            'banners.view', 'banners.create', 'banners.update', 'banners.delete', 'banners.reorder',
            'media.view', 'media.upload', 'media.update', 'media.delete', 'settings.view', 'settings.update', 'seo.view', 'seo.update',
            'social-links.view', 'social-links.create', 'social-links.update', 'social-links.delete', 'social-links.reorder',
            'redirects.view', 'redirects.create', 'redirects.update', 'redirects.delete',
            'contributors.view', 'contributors.create', 'contributors.update', 'contributors.delete', 'contributors.publish', 'contributors.feature', 'contributors.reorder',
            'articles.view', 'articles.create', 'articles.update', 'articles.delete', 'articles.publish', 'articles.feature', 'courses.view', 'courses.create', 'courses.update', 'courses.delete', 'courses.publish', 'courses.feature', 'courses.curriculum.manage', 'courses.faculty.manage', 'courses.faq.manage', 'publications.view', 'publications.create', 'publications.update', 'publications.delete', 'publications.publish', 'publications.feature', 'publications.preview.manage', 'publications.contributors.manage', 'resources.view', 'resources.create', 'resources.update', 'resources.delete', 'resources.publish', 'resources.feature', 'resources.file.manage', 'resources.preview.manage', 'entitlements.view', 'entitlements.grant', 'entitlements.revoke', 'downloads.view',
            'books.view', 'books.create', 'books.update', 'books.delete', 'books.publish', 'books.feature', 'books.images.manage', 'authors.view', 'authors.create', 'authors.update', 'authors.delete', 'publishers.view', 'publishers.create', 'publishers.update', 'publishers.delete',
            'inventory.view', 'inventory.adjust', 'inventory.increase', 'inventory.decrease', 'inventory.threshold.update', 'inventory.movements.view',
            'coupons.view', 'coupons.create', 'coupons.update', 'coupons.delete', 'coupons.activate', 'coupon-usages.view',
            'shipping.view', 'shipping.settings.view', 'shipping.settings.update', 'shipping.providers.view', 'shipping.providers.configure', 'shipping.providers.toggle', 'shipping.providers.test', 'shipping.rates.view', 'shipping.serviceability.view',
            'orders.view', 'orders.update-status', 'orders.cancel', 'orders.customer.view', 'order-status-history.view',
            'payment-settings.view', 'payment-settings.update', 'payment-providers.view', 'payment-providers.configure', 'payment-providers.toggle', 'payment-providers.test', 'payment-providers.default', 'payment-attempts.view', 'payment-transactions.view', 'payment-reconciliation.run', 'refunds.view',
            'invoice-settings.view', 'invoice-settings.update', 'invoices.view', 'invoices.issue', 'invoices.download', 'invoices.regenerate', 'invoices.void',
            'shipments.view', 'shipments.create', 'shipments.update', 'shipments.cancel', 'shipments.awb.assign', 'shipments.pickup.schedule', 'shipments.label.generate', 'shipments.label.download', 'shipments.manifest.generate', 'shipments.manifest.download', 'shipments.tracking.refresh', 'shipments.reconcile', 'shipment-attempts.view', 'shipment-events.view', 'shipping-webhooks.view',
            'notifications.view', 'notifications.settings.view', 'notifications.settings.update', 'notifications.email.test', 'notifications.logs.view', 'notifications.logs.retry', 'notifications.templates.view', 'notifications.templates.update',
            'enquiries.view', 'enquiries.manage', 'support-tickets.view', 'support-tickets.manage', 'workshops.view', 'workshops.manage', 'careers.view', 'careers.manage',
            'notices.view', 'notices.create', 'notices.update', 'notices.delete', 'notices.publish', 'notices.feature', 'notices.pin', 'gallery.view', 'gallery.create', 'gallery.update', 'gallery.delete', 'gallery.publish', 'gallery.feature', 'gallery.images.manage', 'gallery.images.reorder', 'videos.view', 'videos.create', 'videos.update', 'videos.delete', 'videos.publish', 'videos.feature',
        ],
        'content-manager' => ['admin.dashboard.access', 'notices.view', 'notices.create', 'notices.update', 'notices.delete', 'notices.publish', 'notices.feature', 'notices.pin', 'gallery.view', 'gallery.create', 'gallery.update', 'gallery.delete', 'gallery.publish', 'gallery.feature', 'gallery.images.manage', 'gallery.images.reorder', 'videos.view', 'videos.create', 'videos.update', 'videos.delete', 'videos.publish', 'videos.feature', 'notifications.templates.view', 'notifications.templates.update', 'books.view', 'resources.view', 'courses.view', 'publications.view', 'engineering-disciplines.view', 'categories.view', 'categories.create', 'categories.update', 'categories.delete', 'categories.reorder', 'topics.view', 'topics.create', 'topics.update', 'topics.delete', 'topics.reorder', 'tags.view', 'tags.create', 'tags.update', 'tags.delete', 'pages.view', 'pages.create', 'pages.update', 'pages.publish', 'banners.view', 'banners.create', 'banners.update', 'banners.delete', 'banners.reorder', 'media.view', 'media.upload', 'media.update', 'media.delete', 'seo.view', 'seo.update', 'social-links.view', 'social-links.update', 'contributors.view', 'contributors.create', 'contributors.update', 'contributors.delete', 'contributors.publish', 'contributors.feature', 'contributors.reorder', 'articles.view', 'articles.create', 'articles.update', 'articles.delete', 'articles.publish', 'articles.feature'],
        'course-manager' => ['admin.dashboard.access', 'books.view', 'resources.view', 'publications.view', 'courses.view', 'courses.create', 'courses.update', 'courses.delete', 'courses.publish', 'courses.feature', 'courses.curriculum.manage', 'courses.faculty.manage', 'courses.faq.manage', 'engineering-disciplines.view', 'course-levels.view', 'course-levels.create', 'course-levels.update', 'course-levels.delete', 'topics.view', 'media.view', 'media.upload', 'seo.view', 'contributors.view', 'articles.view'],
        'publication-manager' => ['admin.dashboard.access', 'books.view', 'resources.view', 'resources.create', 'resources.update', 'resources.delete', 'resources.publish', 'resources.feature', 'resources.file.manage', 'resources.preview.manage', 'entitlements.view', 'entitlements.grant', 'entitlements.revoke', 'downloads.view', 'courses.view', 'publications.view', 'publications.create', 'publications.update', 'publications.delete', 'publications.publish', 'publications.feature', 'publications.preview.manage', 'publications.contributors.manage', 'engineering-disciplines.view', 'publication-types.view', 'publication-types.create', 'publication-types.update', 'publication-types.delete', 'resource-types.view', 'resource-types.create', 'resource-types.update', 'resource-types.delete', 'media.view', 'media.upload', 'seo.view', 'contributors.view', 'articles.view'],
        'book-manager' => ['admin.dashboard.access', 'books.view', 'books.create', 'books.update', 'books.delete', 'books.publish', 'books.feature', 'books.images.manage', 'authors.view', 'authors.create', 'authors.update', 'authors.delete', 'publishers.view', 'publishers.create', 'publishers.update', 'publishers.delete', 'inventory.view', 'inventory.adjust', 'inventory.increase', 'inventory.decrease', 'inventory.threshold.update', 'inventory.movements.view', 'coupons.view', 'coupons.create', 'coupons.update', 'resources.view', 'publications.view', 'courses.view', 'engineering-disciplines.view', 'categories.view', 'media.view', 'media.upload', 'seo.view', 'seo.update', 'contributors.view', 'articles.view'],
        'order-manager' => ['admin.dashboard.access', 'notifications.view', 'notifications.logs.view', 'books.view', 'inventory.view', 'inventory.movements.view', 'coupons.view', 'coupon-usages.view', 'shipping.view', 'shipping.settings.view', 'shipping.providers.view', 'shipping.rates.view', 'shipping.serviceability.view', 'orders.view', 'orders.update-status', 'orders.cancel', 'orders.customer.view', 'order-status-history.view', 'payment-settings.view', 'payment-providers.view', 'payment-attempts.view', 'payment-transactions.view', 'payment-reconciliation.run', 'refunds.view', 'invoice-settings.view', 'invoices.view', 'invoices.issue', 'invoices.download', 'invoices.regenerate', 'shipments.view', 'shipments.create', 'shipments.update', 'shipments.cancel', 'shipments.awb.assign', 'shipments.pickup.schedule', 'shipments.label.generate', 'shipments.label.download', 'shipments.manifest.generate', 'shipments.manifest.download', 'shipments.tracking.refresh', 'shipments.reconcile', 'shipment-attempts.view', 'shipment-events.view', 'shipping-webhooks.view'],
        'support-manager' => ['admin.dashboard.access', 'notifications.view', 'notifications.logs.view', 'notifications.logs.retry', 'books.view', 'inventory.view', 'entitlements.view', 'downloads.view', 'coupons.view', 'coupon-usages.view', 'shipping.view', 'shipping.providers.view', 'shipping.rates.view', 'shipping.serviceability.view', 'orders.view', 'orders.customer.view', 'order-status-history.view', 'enquiries.view', 'enquiries.manage', 'support-tickets.view', 'support-tickets.manage', 'workshops.view', 'workshops.manage', 'careers.view', 'careers.manage'],
        'customer' => [],
    ],
];
