<?php

return [
    'cache_ttl' => 3600,
    'media_disk' => env('CMS_MEDIA_DISK', 'public'),
    'media_max_kb' => 5120,
    'media_mimes' => ['jpg', 'jpeg', 'png', 'webp', 'pdf'],
    'page_types' => ['standard', 'legal', 'system', 'landing'],
    'page_statuses' => ['draft', 'published', 'archived'],
    'banner_placements' => ['homepage-hero', 'inner-page', 'campaign'],
    'robots' => ['index,follow', 'noindex,follow', 'noindex,nofollow'],
    'redirect_codes' => [301, 302, 307, 308],
    'setting_keys' => [
        'site_name' => ['group' => 'general', 'type' => 'string', 'public' => true],
        'site_tagline' => ['group' => 'general', 'type' => 'string', 'public' => true],
        'publications_enabled' => ['group' => 'visibility', 'type' => 'boolean', 'public' => true],
        'referral_reward_rupees' => ['group' => 'commerce', 'type' => 'integer', 'public' => false],
        'referral_min_withdrawal_rupees' => ['group' => 'commerce', 'type' => 'integer', 'public' => false],
        'default_currency' => ['group' => 'general', 'type' => 'string', 'public' => true],
        'default_timezone' => ['group' => 'general', 'type' => 'string', 'public' => true],
        'default_email' => ['group' => 'contact', 'type' => 'email', 'public' => true],
        'default_phone' => ['group' => 'contact', 'type' => 'string', 'public' => true],
        'support_email' => ['group' => 'contact', 'type' => 'email', 'public' => true],
        'support_phone' => ['group' => 'contact', 'type' => 'string', 'public' => true],
        'contact_address' => ['group' => 'contact', 'type' => 'text', 'public' => true],
        'working_hours' => ['group' => 'contact', 'type' => 'string', 'public' => true],
        'map_url' => ['group' => 'contact', 'type' => 'url', 'public' => true],
        'whatsapp_number' => ['group' => 'contact', 'type' => 'string', 'public' => true],
        'logo_media_id' => ['group' => 'branding', 'type' => 'media', 'public' => true],
        'footer_logo_media_id' => ['group' => 'branding', 'type' => 'media', 'public' => true],
        'favicon_media_id' => ['group' => 'branding', 'type' => 'media', 'public' => true],
        'footer_tagline' => ['group' => 'footer', 'type' => 'string', 'public' => true],
        'copyright_text' => ['group' => 'footer', 'type' => 'string', 'public' => true],
        'default_meta_title' => ['group' => 'seo', 'type' => 'string', 'public' => true],
        'default_meta_description' => ['group' => 'seo', 'type' => 'text', 'public' => true],
        'default_og_media_id' => ['group' => 'seo', 'type' => 'media', 'public' => true],
        'default_robots' => ['group' => 'seo', 'type' => 'string', 'public' => true],
        'internal_editor_note' => ['group' => 'internal', 'type' => 'text', 'public' => false],
    ],
];
