import { ArrowRight, BookOpen, CaretDown, CheckCircle, FileText } from "@phosphor-icons/react";

export function AccessBadge({type}){return <span className={`access-badge access-badge--${type.toLowerCase()}`}>{type}</span>}
export function CourseCard({course}){return <article className="catalog-card course-list-card"><img src={course.image} alt=""/><div><small>{course.discipline}</small><h3>{course.title}</h3><p>{course.description}</p><div className="catalog-meta"><span>{course.mode}</span><span>{course.level}</span></div><a href={`/courses/${course.slug}`}>View Course <ArrowRight/></a></div></article>}
export function PublicationCard({publication}){return <article className="publication-list-card"><img src={publication.image} alt={`${publication.title} cover`}/><div><small>{publication.discipline}</small><h3>{publication.title}</h3><p>{publication.type} · {publication.issue}</p><AccessBadge type={publication.access}/><a href={`/publications/${publication.slug}`}>View Publication <ArrowRight/></a></div></article>}
export function ResourceCard({resource}){return <article className="resource-list-card"><FileText aria-hidden="true"/><div><small>{resource.discipline}</small><h3>{resource.title}</h3><p>{resource.description}</p><div><span>{resource.type}</span><AccessBadge type={resource.access}/></div><a href={`/resources/${resource.slug}`}>View Resource <ArrowRight/></a></div></article>}
export function FilterBar({children}){return <div className="catalog-tools">{children}</div>}
export function FilterField({label,children,className=""}){return <label className={className}><span>{label}</span>{children}</label>}
export function Accordion({items,className=""}){return <div className={`accordion ${className}`}>{items.map((item,index)=><details key={item.title} open={index===0}><summary><span>{item.title}</span><CaretDown aria-hidden="true"/></summary><div>{item.content}</div></details>)}</div>}
export function OutcomeList({items}){return <ul className="outcome-list">{items.map(x=><li key={x}><CheckCircle aria-hidden="true" weight="fill"/><span>{x}</span></li>)}</ul>}
export function DetailSidebar({rows,cta,href="#register"}){return <aside className="detail-sidebar"><h2>Course information</h2><dl>{rows.map(([term,value])=><div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl>{cta&&<a className="button button--primary" href={href}><BookOpen/> {cta}</a>}</aside>}
