<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:28px 34px}body{font-family:DejaVu Sans,sans-serif;color:#102a56;font-size:10px;margin:0}.header{border-bottom:3px solid #0868d7;padding-bottom:14px;margin-bottom:16px}.brand{font-size:24px;font-weight:bold;color:#052c66}.title{float:right;text-align:right;font-size:22px}.meta{font-size:9px;color:#536987}.grid{width:100%;margin:12px 0;border-collapse:collapse}.grid td{width:50%;vertical-align:top;padding:10px;border:1px solid #dbe7f5}.items{width:100%;border-collapse:collapse;margin-top:16px}.items th{background:#0b4f9c;color:white;padding:8px;text-align:left}.items td{border-bottom:1px solid #dbe7f5;padding:8px}.num{text-align:right}.totals{width:42%;margin-left:auto;margin-top:12px;border-collapse:collapse}.totals td{padding:5px;border-bottom:1px solid #dbe7f5}.grand{font-size:13px;font-weight:bold;background:#edf6ff}.footer{margin-top:24px;border-top:1px solid #dbe7f5;padding-top:12px;color:#536987}.void{color:#b00020;border:3px solid #b00020;padding:8px;text-align:center;font-size:18px}.page-number:after{content:counter(page)}
</style></head><body>
@php($seller=$invoice->seller_snapshot) @php($customer=$invoice->customer_snapshot) @php($ship=$invoice->shipping_address_snapshot) @php($view=$invoice->presentation_snapshot)
@if($invoice->status==='void')<div class="void">VOID - {{ $invoice->void_reason }}</div>@endif
<div class="header">@if($seller['logo_path'] && Storage::disk('local')->exists($seller['logo_path']))<img src="{{ Storage::disk('local')->path($seller['logo_path']) }}" style="max-height:50px;max-width:220px">@else<span class="brand">{{ $seller['display_name'] }}</span>@endif<span class="title">{{ $invoice->invoice_type==='tax_invoice'?'TAX INVOICE':'INVOICE' }}</span><div>{{ $seller['business_name'] }}</div></div>
<table class="grid"><tr><td><strong>Invoice</strong><br>No: {{ $invoice->invoice_number }}<br>Date: {{ $invoice->issued_at->format('d M Y') }}<br>Order: {{ $invoice->order->order_number }}</td><td><strong>Seller</strong><br>{{ $seller['business_name'] }}@if($seller['address_line_1'])<br>{{ $seller['address_line_1'] }} {{ $seller['address_line_2'] }}@endif @if($seller['city']||$seller['state'])<br>{{ collect([$seller['city'],$seller['state']])->filter()->join(', ') }} {{ $seller['postal_code'] }}@endif<br>{{ $seller['country'] }}<br>@if($seller['gstin'])GSTIN: {{ $seller['gstin'] }}<br>@endif @if($seller['pan'])PAN: {{ $seller['pan'] }}@endif</td></tr><tr><td><strong>Bill To</strong><br>{{ $customer['name'] }}<br>{{ $customer['email'] }}<br>{{ $customer['mobile'] }}</td><td><strong>Ship To</strong><br>{{ $ship['name'] }}<br>{{ $ship['address_line_1'] }} {{ $ship['address_line_2'] }}<br>{{ $ship['city'] }}, {{ $ship['state'] }} {{ $ship['postal_code'] }}<br>{{ $ship['country'] }}</td></tr></table>
<table class="items"><thead><tr><th>#</th><th>Item</th><th>SKU</th>@if($view['show_hsn'])<th>HSN/SAC</th>@endif<th class="num">Qty</th><th class="num">Rate</th>@if($view['show_discount'])<th class="num">Discount</th>@endif<th class="num">Amount</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->title }}</td><td>{{ $item->sku }}</td>@if($view['show_hsn'])<td>{{ $item->hsn_code ?: '-' }}</td>@endif<td class="num">{{ $item->quantity }}</td><td class="num">{{ number_format($item->unit_price,2) }}</td>@if($view['show_discount'])<td class="num">{{ number_format($item->discount_amount,2) }}</td>@endif<td class="num">{{ number_format($item->line_total,2) }}</td></tr>@endforeach</tbody></table>
<table class="totals"><tr><td>Subtotal</td><td class="num">{{ $invoice->currency }} {{ number_format($invoice->subtotal,2) }}</td></tr>@if($view['show_discount'])<tr><td>Discount</td><td class="num">- {{ number_format($invoice->discount_amount,2) }}</td></tr>@endif @if($view['show_shipping'])<tr><td>Shipping</td><td class="num">{{ number_format($invoice->shipping_amount,2) }}</td></tr>@endif @if($invoice->cod_charge>0)<tr><td>COD charge</td><td class="num">{{ number_format($invoice->cod_charge,2) }}</td></tr>@endif @if($invoice->total_tax>0)<tr><td>Tax</td><td class="num">{{ number_format($invoice->total_tax,2) }}</td></tr>@endif<tr class="grand"><td>Grand Total</td><td class="num">{{ $invoice->currency }} {{ number_format($invoice->grand_total,2) }}</td></tr></table>
@if($view['show_payment_method'])<p><strong>Payment:</strong> {{ strtoupper($invoice->payment_method) }} / {{ strtoupper($invoice->payment_status_snapshot) }} @if($view['show_payment_reference']&&$invoice->payment_reference_snapshot) - Ref: {{ $invoice->payment_reference_snapshot }}@endif</p>@endif
<div class="footer">@if($view['terms'])<p><strong>Terms:</strong> {{ $view['terms'] }}</p>@endif @if($view['declaration'])<p><strong>Declaration:</strong> {{ $view['declaration'] }}</p>@endif @if($view['signature_path'] && Storage::disk('local')->exists($view['signature_path']))<p style="text-align:right"><img src="{{ Storage::disk('local')->path($view['signature_path']) }}" style="max-height:45px;max-width:150px"></p>@endif @if($view['authorized_signatory_name'])<p style="text-align:right"><strong>{{ $view['authorized_signatory_name'] }}</strong><br>{{ $view['authorized_signatory_designation'] }}</p>@endif<p>{{ $view['footer_text'] }} <span style="float:right">Page <span class="page-number"></span></span></p></div>
</body></html>
