import { useEffect, useState } from 'react';
import { InnerPageHeader } from '../components/shared/InnerPageComponents';
import { adminOperationsService as api } from '../services/adminOperationsService';
const unpack = response => response?.data?.data || response?.data || [];
const tabs = ['enquiries','tickets','workshops','careers','applications'];
const statuses = { enquiries: ['new','in_progress','resolved','closed'], tickets: ['open','in_progress','awaiting_customer','customer_reply','resolved','closed'], applications: ['received','reviewing','shortlisted','rejected','hired'] };
const workshopDefaults = { title: '', type: 'workshop', short_description: '', description: '', start_at: '', end_at: '', mode: 'online', venue: '', meeting_url: '', capacity: '', registration_type: 'free', fee: '0', currency: 'INR', status: 'draft', is_featured: false };
const jobDefaults = { title: '', department: '', location: '', employment_type: 'full_time', work_mode: 'onsite', summary: '', description: '', responsibilities: '', requirements: '', preferred_skills: '', application_deadline: '', status: 'draft', is_featured: false };
const workshopFields = [['title','Title','text',true],['type','Type','select',true,['workshop','webinar','seminar','training']],['start_at','Start time','datetime-local',true],['end_at','End time','datetime-local',true],['mode','Mode','select',true,['online','offline','hybrid']],['venue','Venue','text'],['meeting_url','Meeting URL','url'],['capacity','Capacity','number'],['registration_type','Registration','select',true,['free','paid']],['fee','Fee','number'],['status','Status','select',true,['draft','published','cancelled','completed']],['short_description','Summary','textarea'],['description','Description','textarea',true]];
const jobFields = [['title','Job title','text',true],['department','Department','text',true],['location','Location','text',true],['employment_type','Employment type','select',true,['full_time','part_time','contract','internship']],['work_mode','Work mode','select',true,['onsite','remote','hybrid']],['application_deadline','Deadline','date'],['status','Status','select',true,['draft','published','closed']],['summary','Summary','textarea',true],['description','Description','textarea',true],['responsibilities','Responsibilities','textarea'],['requirements','Requirements','textarea'],['preferred_skills','Preferred skills','textarea']];
export function AdminOperationsPage() {
  const [tab, setTab] = useState('enquiries'), [items, setItems] = useState([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const [editing, setEditing] = useState(null), [form, setForm] = useState(null), [detail, setDetail] = useState(null), [reply, setReply] = useState(''), [internal, setInternal] = useState(false), [deleteTarget, setDeleteTarget] = useState(null);
  async function load(type = tab) { setLoading(true); try { const fetch = { enquiries: api.enquiries, tickets: api.tickets, workshops: api.workshops, careers: api.jobs, applications: api.applications }[type]; setItems(unpack(await fetch())); } catch (error) { setMessage(error.message); } finally { setLoading(false); } }
  useEffect(() => { setMessage(''); setDetail(null); load(tab); }, [tab]);
  async function status(item, value) { setBusy(true); try { if (tab === 'enquiries') await api.updateEnquiry(item.id, { status: value }); if (tab === 'tickets') await api.updateTicket(item.id, { status: value }); if (tab === 'applications') await api.updateApplication(item.id, { status: value }); setMessage('Status updated.'); await load(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  function open(item = null) { const values = { ...(tab === 'workshops' ? workshopDefaults : jobDefaults), ...item }; if (tab === 'workshops') { values.start_at = values.start_at?.slice(0, 16) || ''; values.end_at = values.end_at?.slice(0, 16) || ''; } if (tab === 'careers') values.application_deadline = values.application_deadline?.slice(0, 10) || ''; setForm(values); setEditing({ id: item?.id || null }); }
  function set(key, value) { setForm(current => ({ ...current, [key]: value })); }
  async function save(event) { event.preventDefault(); setBusy(true); try { const payload = { ...form }; for (const key of ['id','created_at','updated_at','deleted_at','published_at','created_by']) delete payload[key]; if (tab === 'workshops') { payload.capacity = payload.capacity ? Number(payload.capacity) : null; payload.fee = Number(payload.fee || 0); await api.saveWorkshop(payload, editing.id); } else await api.saveJob(payload, editing.id); setEditing(null); setMessage('Saved successfully.'); await load(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function remove() { setBusy(true); try { await (tab === 'workshops' ? api.deleteWorkshop(deleteTarget.id) : api.deleteJob(deleteTarget.id)); setDeleteTarget(null); setMessage('Removed successfully.'); await load(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function view(item) { setBusy(true); try { setDetail(unpack(await (tab === 'enquiries' ? api.enquiry(item.id) : api.ticket(item.id)))); setReply(''); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function sendReply(event) { event.preventDefault(); setBusy(true); try { if (tab === 'enquiries') await api.noteEnquiry(detail.id, reply); else await api.replyTicket(detail.id, reply, internal); setReply(''); setDetail(unpack(await (tab === 'enquiries' ? api.enquiry(detail.id) : api.ticket(detail.id)))); setMessage(tab === 'enquiries' || internal ? 'Internal note saved.' : 'Reply sent to the customer.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  const fields = tab === 'workshops' ? workshopFields : jobFields;
  return <div className="admin-module"><InnerPageHeader eyebrow="Operations / Customers" title="Enquiries, Support & Opportunities" description="Handle customer requests and publish workshops or job openings." />
    <div className="account-filters admin-tabs">{tabs.map(value => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)}>{value}</button>)}</div>
    <section className="admin-data-panel"><header><div><h2>{tab}</h2><p>{items.length} records</p></div>{['workshops','careers'].includes(tab) && <button className="button button--primary" onClick={() => open()}>＋ Add {tab === 'workshops' ? 'workshop' : 'job'}</button>}</header>
      {loading ? <div className="admin-list-loading">Loading…</div> : items.length ? <div className="admin-content-list">{items.map(item => <article key={item.id}><span className="admin-row-index">{String(item.id).padStart(2, '0')}</span><div><strong>{item.reference_number || item.ticket_number || item.title || item.name}</strong><small>{item.email || item.department || item.type} · {item.subject || item.location || item.status}</small></div><span className={`admin-status admin-status--${item.status}`}>{item.status}</span><div className="admin-crud-actions">{statuses[tab] ? <><select aria-label="Update status" value={item.status} disabled={busy} onChange={event => status(item, event.target.value)}>{statuses[tab].map(value => <option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select>{tab !== 'applications' && <button onClick={() => view(item)}>View / Reply</button>}</> : <><button onClick={() => open(item)}>Edit</button><button className="danger" onClick={() => setDeleteTarget(item)}>Delete</button></>}</div></article>)}</div> : <div className="admin-empty"><h3>No {tab} found</h3><p>New records will appear here.</p></div>}</section>
    {message && <p className="form-status" role="status">{message}</p>}
    {editing && <div className="admin-modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true"><header><div><small>OPPORTUNITIES</small><h2>{editing.id ? 'Edit' : 'Add'} {tab === 'workshops' ? 'workshop' : 'job opening'}</h2></div><button onClick={() => setEditing(null)} aria-label="Close">×</button></header><form onSubmit={save}><div className="admin-editor-grid">{fields.map(([name,label,kind,required,options]) => <label key={name} className={kind === 'textarea' ? 'wide' : ''}><span>{label}{required && ' *'}</span>{kind === 'textarea' ? <textarea rows={name === 'description' ? 7 : 3} required={required} value={form[name] || ''} onChange={event => set(name, event.target.value)} /> : kind === 'select' ? <select value={form[name] || ''} required={required} onChange={event => set(name, event.target.value)}>{options.map(value => <option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select> : <input type={kind} required={required} value={form[name] || ''} onChange={event => set(name, event.target.value)} />}</label>)}<label className="admin-checkbox"><input type="checkbox" checked={Boolean(form.is_featured)} onChange={event => set('is_featured', event.target.checked)} /><span>Featured</span></label></div><footer><button type="button" className="button button--secondary" onClick={() => setEditing(null)}>Cancel</button><button className="button button--primary" disabled={busy}>{busy ? 'Saving…' : 'Save'}</button></footer></form></section></div>}
    {detail && <div className="admin-modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true"><header><div><small>CUSTOMER REQUEST</small><h2>{detail.subject || detail.ticket_number}</h2></div><button onClick={() => setDetail(null)} aria-label="Close">×</button></header><div className="admin-detail-body"><p><strong>{detail.name}</strong> · {detail.email}</p><p>{detail.message || detail.description}</p>{(detail.notes || detail.messages || []).map(entry => <div className="admin-detail-note" key={entry.id}>{entry.note || entry.message}</div>)}</div><form onSubmit={sendReply}><label className="admin-reply-label">{tab === 'enquiries' ? 'Internal note' : 'Reply to customer'}<textarea required rows="4" value={reply} onChange={event => setReply(event.target.value)} /></label>{tab === 'tickets' && <label className="admin-checkbox"><input type="checkbox" checked={internal} onChange={event => setInternal(event.target.checked)} /> Save as internal note</label>}<footer><button type="button" className="button button--secondary" onClick={() => setDetail(null)}>Close</button><button className="button button--primary" disabled={busy}>Save {tab === 'enquiries' || internal ? 'note' : 'reply'}</button></footer></form></section></div>}
    {deleteTarget && <div className="admin-modal-backdrop"><section className="admin-confirm" role="alertdialog" aria-modal="true"><h2>Remove {deleteTarget.title}?</h2><p>Existing registrations or applications may prevent deletion.</p><div><button className="button button--secondary" onClick={() => setDeleteTarget(null)}>Cancel</button><button className="button admin-delete-button" disabled={busy} onClick={remove}>Delete</button></div></section></div>}
  </div>;
}
