import { useEffect, useMemo, useState } from 'react';
import { adminCommerceService as api } from '../services/adminCommerceService';
import { InnerPageHeader } from '../components/shared/InnerPageComponents';

const unwrap = (response) => response?.data?.data || response?.data || [];
const emptyBook = { title: '', sku: '', isbn: '', short_description: '', description: '', mrp: '', selling_price: '', currency: 'INR', status: 'draft', format: 'paperback', language: 'English', edition: '', publication_year: '', pages: '', engineering_discipline_id: '', discipline_ids: [], category_id: '', publisher_id: '', cover_media_id: '', authors: [], gallery: [], weight_grams: '', length_cm: '', width_cm: '', height_cm: '', shipping_enabled: true, is_featured: false, is_new_arrival: false };
const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value || 0));
const optionalNumber = (value) => value === '' || value == null ? null : Number(value);

export function AdminBooksPage() {
  const [books, setBooks] = useState([]), [masters, setMasters] = useState({ authors: [], publishers: [], disciplines: [], categories: [], media: [] });
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [search, setSearch] = useState('');
  const [editor, setEditor] = useState(null), [book, setBook] = useState(emptyBook), [stock, setStock] = useState(null), [stockTarget, setStockTarget] = useState(''), [lowStockThreshold, setLowStockThreshold] = useState(''), [stockReason, setStockReason] = useState('Stock count correction'), [deleteTarget, setDeleteTarget] = useState(null), [quickKind, setQuickKind] = useState(null), [quickName, setQuickName] = useState('');
  const visible = useMemo(() => books.filter(item => `${item.title} ${item.sku}`.toLowerCase().includes(search.toLowerCase())), [books, search]);

  async function loadBooks() { setLoading(true); try { setBooks(unwrap(await api.books())); } catch (error) { setMessage(error.message); } finally { setLoading(false); } }
  async function loadMasters() { const [authors, publishers, disciplines, categories, media] = await Promise.all([api.authors(), api.publishers(), api.disciplines(), api.categories(), api.media()]); setMasters({ authors: unwrap(authors), publishers: unwrap(publishers), disciplines: unwrap(disciplines), categories: unwrap(categories), media: unwrap(media) }); }
  useEffect(() => { loadBooks(); }, []);
  async function openEditor(item = null) { setBusy(true); setMessage(''); try { await loadMasters(); const detail = item ? unwrap(await api.book(item.id)) : emptyBook; setBook({ ...emptyBook, ...detail, authors: detail.authors || [], gallery: detail.gallery || [], engineering_discipline_id: detail.engineering_discipline_id ?? detail.discipline?.id ?? '', discipline_ids: detail.discipline_ids || (detail.engineering_discipline_id ? [detail.engineering_discipline_id] : []), category_id: detail.category_id ?? detail.category?.id ?? '', publisher_id: detail.publisher_id ?? detail.publisher?.id ?? '', cover_media_id: detail.cover_media_id ?? '' }); setEditor({ id: item?.id || null }); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  function set(name, value) { setBook(current => ({ ...current, [name]: value })); }
  async function upload(file, field) { if (!file) return; setBusy(true); setMessage(''); try { const uploaded = unwrap(await api.uploadMedia(file, `${book.title || 'Book'} ${field === 'cover_media_id' ? 'cover' : 'gallery image'}`)); setMasters(current => ({ ...current, media: [uploaded, ...current.media] })); if (field === 'cover_media_id') set('cover_media_id', uploaded.id); else setBook(current => ({ ...current, gallery: [...current.gallery, { media_id: uploaded.id, url: uploaded.url }] })); setMessage('Image uploaded successfully. Save the book to use it.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function quickCreate(event) { event.preventDefault(); if (!quickName.trim()) return; setBusy(true); try { const create = { authors: api.createAuthor, publishers: api.createPublisher, categories: api.createCategory }[quickKind]; const created = unwrap(await create(quickName.trim())); setMasters(current => ({ ...current, [quickKind]: [...current[quickKind], created] })); if (quickKind === 'authors') setBook(current => ({ ...current, authors: [...current.authors, { id: created.id, name: created.name, role: 'author' }] })); else set(quickKind === 'categories' ? 'category_id' : 'publisher_id', created.id); setQuickKind(null); setQuickName(''); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function save(event) { event.preventDefault(); setBusy(true); setMessage(''); try { const data = { ...book, mrp: Number(book.mrp), selling_price: Number(book.selling_price), engineering_discipline_id: optionalNumber(book.discipline_ids[0]), discipline_ids: book.discipline_ids.map(Number), category_id: optionalNumber(book.category_id), publisher_id: optionalNumber(book.publisher_id), cover_media_id: optionalNumber(book.cover_media_id), publication_year: optionalNumber(book.publication_year), pages: optionalNumber(book.pages), weight_grams: optionalNumber(book.weight_grams), length_cm: optionalNumber(book.length_cm), width_cm: optionalNumber(book.width_cm), height_cm: optionalNumber(book.height_cm), authors: book.authors.map(author => ({ id: author.id, role: author.role || 'author' })), gallery: book.gallery.map(image => ({ media_id: image.media_id, is_primary: Boolean(image.is_primary) })) }; delete data.id; delete data.cover; delete data.discipline; delete data.disciplines; delete data.category; delete data.publisher; delete data.inventory; delete data.seo; delete data.author_summary; delete data.price; delete data.saving_amount; delete data.discount_percentage; delete data.created_by; delete data.updated_by; delete data.created_at; delete data.updated_at; delete data.deleted_at; delete data.published_at; if (!data.sku) delete data.sku; if (!data.slug) delete data.slug; if (data.selling_price > data.mrp) throw new Error('Selling price cannot be higher than MRP.'); const saved = unwrap(await api.saveBook(data, editor?.id)); setMessage(`Book ${editor?.id ? 'updated' : 'created'} successfully.`); setEditor(null); await loadBooks(); if (!editor?.id && saved.id) await openStock(saved); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function openStock(item) { setBusy(true); try { const current = unwrap(await api.inventory(item.id)); setStock({ id: item.id, title: item.title, ...current }); setStockTarget(String(current.stock_quantity ?? 0)); setLowStockThreshold(String(current.low_stock_threshold ?? 5)); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function saveStock(event) { event.preventDefault(); setBusy(true); try { if (Number(stockTarget) !== Number(stock.stock_quantity)) await api.adjustStock(stock.id, { target_quantity: Number(stockTarget), reason: stockReason }); if (Number(lowStockThreshold) !== Number(stock.low_stock_threshold)) await api.setLowStockThreshold(stock.id, Number(lowStockThreshold)); setStock(null); setMessage('Stock and low-stock alert level updated.'); await loadBooks(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function remove() { setBusy(true); try { await api.deleteBook(deleteTarget.id); setDeleteTarget(null); setMessage('Book removed from the catalogue.'); await loadBooks(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  const selectedCover = masters.media.find(media => Number(media.id) === Number(book.cover_media_id));
  return <div className="admin-module admin-books"><InnerPageHeader eyebrow="Store / Products" title="Book Catalogue" description="Manage book covers, descriptions, prices, availability and shipping details in one place." />
    <div className="admin-module-summary"><div><strong>{books.length}</strong><span>books in catalogue</span></div><label><span>Find a book</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search title or SKU" /></label></div>
    <section className="admin-data-panel"><header><div><h2>Products</h2><p>Cover, price and inventory at a glance.</p></div><button className="button button--primary" onClick={() => openEditor()}>＋ Add book</button></header>
      {loading ? <div className="admin-list-loading">Loading catalogue…</div> : visible.length ? <div className="admin-product-list">{visible.map(item => <article key={item.id}><img src={item.cover?.url || '/books/electrical-power-systems.webp'} alt="" /><div className="admin-product-title"><strong>{item.title}</strong><small>SKU {item.sku || 'Pending'} · {item.author_summary || 'No author'}</small><span className={`admin-status admin-status--${item.status}`}>{item.status}</span></div><div className="admin-product-price"><strong>{money(item.selling_price)}</strong><del>{money(item.mrp)}</del></div><div className="admin-product-stock"><strong>{item.inventory?.stock_quantity ?? 0} in stock</strong><small>{item.inventory?.status || 'Out of stock'}</small></div><div className="admin-crud-actions"><button onClick={() => openEditor(item)}>Edit</button><button onClick={() => openStock(item)}>Stock</button><button className="danger" onClick={() => setDeleteTarget(item)}>Delete</button></div></article>)}</div> : <div className="admin-empty"><h3>No books found</h3><p>Add a product to start your book catalogue.</p><button onClick={() => openEditor()}>Add book</button></div>}
    </section>{message && <p className="form-status" role="status">{message}</p>}
    {editor && <div className="admin-modal-backdrop"><section className="admin-modal admin-product-editor" role="dialog" aria-modal="true" aria-labelledby="book-editor-title"><header><div><small>STORE PRODUCT</small><h2 id="book-editor-title">{editor.id ? 'Edit book' : 'Add a book'}</h2></div><button aria-label="Close editor" onClick={() => setEditor(null)}>×</button></header><form onSubmit={save}><div className="admin-editor-grid">
      <label><span>Book title *</span><input required value={book.title} onChange={event => set('title', event.target.value)} /></label><label><span>SKU (auto-generated if empty)</span><input value={book.sku || ''} onChange={event => set('sku', event.target.value.toUpperCase())} /></label>
      <label><span>ISBN</span><input value={book.isbn || ''} onChange={event => set('isbn', event.target.value)} /></label><fieldset className="admin-book-disciplines"><legend>Engineering disciplines</legend><p>Select every branch this book is relevant to.</p><div className="admin-book-disciplines-actions"><span>{book.discipline_ids.length} of {masters.disciplines.length} branches selected</span><button type="button" disabled={!masters.disciplines.length} onClick={() => set('discipline_ids', masters.disciplines.map(item => Number(item.id)))}>Select all branches</button><button type="button" disabled={!book.discipline_ids.length} onClick={() => set('discipline_ids', [])}>Clear selection</button></div><div className="admin-book-disciplines-options">{masters.disciplines.map(item => <label key={item.id}><input type="checkbox" checked={book.discipline_ids.map(Number).includes(Number(item.id))} onChange={event => set('discipline_ids', event.target.checked ? [...book.discipline_ids, Number(item.id)] : book.discipline_ids.filter(id => Number(id) !== Number(item.id)))} /><span>{item.name}</span></label>)}</div></fieldset>
      <label><span>Category</span><div className="admin-inline-input"><select value={book.category_id || ''} onChange={event => set('category_id', event.target.value)}><option value="">Select category</option>{masters.categories.filter(item => item.is_active !== false && ['book','general'].includes(item.context)).map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select><button type="button" aria-label="Add book category" onClick={() => { setQuickKind('categories'); setQuickName(''); }}>＋ New</button></div></label><label><span>Publisher</span><div className="admin-inline-input"><select value={book.publisher_id || ''} onChange={event => set('publisher_id', event.target.value)}><option value="">Select publisher</option>{masters.publishers.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select><button type="button" onClick={() => { setQuickKind('publishers'); setQuickName(''); }}>＋</button></div></label>
      <label className="wide"><span>Authors</span><div className="admin-inline-input"><select value="" onChange={event => { const author = masters.authors.find(item => String(item.id) === event.target.value); if (author && !book.authors.some(item => item.id === author.id)) set('authors', [...book.authors, { id: author.id, name: author.name, role: 'author' }]); }}><option value="">Add an author</option>{masters.authors.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select><button type="button" onClick={() => { setQuickKind('authors'); setQuickName(''); }}>＋ New</button></div><div className="admin-chips">{book.authors.map(author => <button type="button" key={author.id} onClick={() => set('authors', book.authors.filter(item => item.id !== author.id))}>{author.name} ×</button>)}</div></label>
      <label><span>MRP (₹) *</span><input type="number" required min="0" step="0.01" value={book.mrp} onChange={event => set('mrp', event.target.value)} /></label><label><span>Selling price (₹) *</span><input type="number" required min="0" step="0.01" value={book.selling_price} onChange={event => set('selling_price', event.target.value)} /></label>
      <label><span>Status</span><select value={book.status} onChange={event => set('status', event.target.value)}>{['draft','published','archived','discontinued'].map(value => <option key={value} value={value}>{value}</option>)}</select></label><label><span>Format</span><select value={book.format || 'paperback'} onChange={event => set('format', event.target.value)}>{['paperback','hardcover','spiral','other'].map(value => <option key={value} value={value}>{value}</option>)}</select></label>
      <label className="wide"><span>Book cover</span><div className="admin-image-picker">{selectedCover?.url && <img src={selectedCover.url} alt="Selected book cover" />}<select value={book.cover_media_id || ''} onChange={event => set('cover_media_id', event.target.value)}><option value="">Choose from media library</option>{masters.media.filter(item => item.mime_type?.startsWith('image/')).map(item => <option value={item.id} key={item.id}>{item.title || item.original_name}</option>)}</select><input aria-label="Upload book cover" type="file" accept="image/png,image/jpeg,image/webp" onChange={event => upload(event.target.files[0], 'cover_media_id')} /></div></label>
      <label className="wide"><span>Additional images</span><div className="admin-inline-input"><select value="" onChange={event => { const image = masters.media.find(item => String(item.id) === event.target.value); if (image && !book.gallery.some(item => Number(item.media_id) === image.id)) set('gallery', [...book.gallery, { media_id: image.id, url: image.url }]); }}><option value="">Add from media library</option>{masters.media.filter(item => item.mime_type?.startsWith('image/')).map(item => <option value={item.id} key={item.id}>{item.title || item.original_name}</option>)}</select><input aria-label="Upload gallery image" type="file" accept="image/png,image/jpeg,image/webp" onChange={event => upload(event.target.files[0], 'gallery')} /></div><div className="admin-gallery-list">{book.gallery.map(image => <div key={image.media_id}><img src={image.url || masters.media.find(item => item.id === Number(image.media_id))?.url} alt="" /><button type="button" onClick={() => set('gallery', book.gallery.filter(item => item.media_id !== image.media_id))}>Remove</button></div>)}</div></label>
      <label><span>Edition</span><input value={book.edition || ''} onChange={event => set('edition', event.target.value)} /></label><label><span>Publication year</span><input type="number" min="1000" value={book.publication_year || ''} onChange={event => set('publication_year', event.target.value)} /></label><label><span>Pages</span><input type="number" min="1" value={book.pages || ''} onChange={event => set('pages', event.target.value)} /></label><label><span>Weight in grams</span><input type="number" min="1" value={book.weight_grams || ''} onChange={event => set('weight_grams', event.target.value)} /></label>
      <label><span>Length (cm)</span><input type="number" min="0" step="0.01" value={book.length_cm || ''} onChange={event => set('length_cm', event.target.value)} /></label><label><span>Width (cm)</span><input type="number" min="0" step="0.01" value={book.width_cm || ''} onChange={event => set('width_cm', event.target.value)} /></label><label><span>Height (cm)</span><input type="number" min="0" step="0.01" value={book.height_cm || ''} onChange={event => set('height_cm', event.target.value)} /></label><label><span>Language</span><input value={book.language || ''} onChange={event => set('language', event.target.value)} /></label>
      <label className="wide"><span>Short description</span><textarea rows="3" value={book.short_description || ''} onChange={event => set('short_description', event.target.value)} /></label><label className="wide"><span>Full description *</span><textarea rows="7" required value={book.description || ''} onChange={event => set('description', event.target.value)} /></label>
      <label className="admin-checkbox"><input type="checkbox" checked={Boolean(book.shipping_enabled)} onChange={event => set('shipping_enabled', event.target.checked)} /><span>Enable shipping</span></label><label className="admin-checkbox"><input type="checkbox" checked={Boolean(book.is_featured)} onChange={event => set('is_featured', event.target.checked)} /><span>Feature on website</span></label><label className="admin-checkbox"><input type="checkbox" checked={Boolean(book.is_new_arrival)} onChange={event => set('is_new_arrival', event.target.checked)} /><span>Mark as new arrival</span></label>
    </div><footer><button type="button" className="button button--secondary" onClick={() => setEditor(null)}>Cancel</button><button className="button button--primary" disabled={busy}>{busy ? 'Saving…' : 'Save book'}</button></footer></form></section></div>}
    {quickKind && <div className="admin-modal-backdrop"><section className="admin-confirm admin-stock-dialog" role="dialog" aria-modal="true"><h2>Add {({ authors: 'author', publishers: 'publisher', categories: 'book category' })[quickKind]}</h2><form onSubmit={quickCreate}><label>Name<input autoFocus required maxLength="255" value={quickName} onChange={event => setQuickName(event.target.value)} /></label><div><button type="button" className="button button--secondary" onClick={() => setQuickKind(null)}>Cancel</button><button className="button button--primary" disabled={busy}>Add</button></div></form></section></div>}
    {stock && <div className="admin-modal-backdrop"><section className="admin-confirm admin-stock-dialog" role="dialog" aria-modal="true"><h2>Adjust stock</h2><p>{stock.title}</p><p>Current: <strong>{stock.stock_quantity}</strong> · Reserved: <strong>{stock.reserved_quantity}</strong></p><form onSubmit={saveStock}><label>New total quantity<input type="number" min={stock.reserved_quantity || 0} required value={stockTarget} onChange={event => setStockTarget(event.target.value)} /></label><label>Low-stock alert threshold<input type="number" min="0" required value={lowStockThreshold} onChange={event => setLowStockThreshold(event.target.value)} /></label><label>Reason for stock changes<input required value={stockReason} onChange={event => setStockReason(event.target.value)} /></label><div><button type="button" className="button button--secondary" onClick={() => setStock(null)}>Cancel</button><button className="button button--primary" disabled={busy}>Save stock</button></div></form></section></div>}
    {deleteTarget && <div className="admin-modal-backdrop"><section className="admin-confirm" role="alertdialog" aria-modal="true"><h2>Remove book?</h2><p>{deleteTarget.title} will be removed from the public catalogue.</p><div><button className="button button--secondary" onClick={() => setDeleteTarget(null)}>Cancel</button><button className="button admin-delete-button" disabled={busy} onClick={remove}>Remove book</button></div></section></div>}
  </div>;
}



