import { useEffect, useState } from 'react';
import { InnerPageHeader } from '../components/shared/InnerPageComponents';
import { adminDiscoveryService as api } from '../services/adminDiscoveryService';

const unpack = response => response?.data?.data || response?.data || [];
const today = () => new Date().toISOString().slice(0, 10);
const defaults = {
  notices: { title: '', status: 'draft', short_description: '', content: '', notice_date: today(), featured_media_id: null, external_url: '', is_featured: false },
  gallery: { title: '', status: 'draft', short_description: '', description: '', event_date: '', cover_media_id: null, is_featured: false },
  videos: { title: '', status: 'draft', short_description: '', description: '', video_type: 'youtube', external_video_id: '', external_url: '', thumbnail_media_id: null, published_date: '', is_featured: false },
};
const mediaField = { notices: 'featured_media_id', gallery: 'cover_media_id', videos: 'thumbnail_media_id' };
export function AdminDiscoveryPage() {
  const [tab, setTab] = useState('notices'), [items, setItems] = useState([]), [media, setMedia] = useState([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const [editing, setEditing] = useState(null), [form, setForm] = useState(null), [deleteTarget, setDeleteTarget] = useState(null), [images, setImages] = useState([]), [existingImages, setExistingImages] = useState([]), [imageAlt, setImageAlt] = useState('');
  async function load(type = tab) { setLoading(true); try { setItems(unpack(await api.list(type))); } catch (error) { setMessage(error.message); } finally { setLoading(false); } }
  useEffect(() => { setMessage(''); load(tab); }, [tab]);
  async function open(item = null) { setBusy(true); try { const [assets, album] = await Promise.all([api.media(), tab === 'gallery' && item ? api.album(item.id) : Promise.resolve(null)]); setMedia(unpack(assets)); setForm({ ...defaults[tab], ...(album ? unpack(album) : item) }); setEditing({ id: item?.id || null }); setImages([]); setExistingImages(album ? unpack(album).images || [] : []); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  function set(key, value) { setForm(current => ({ ...current, [key]: value })); }
  async function upload(file) { if (!file) return; setBusy(true); try { const asset = unpack(await api.upload(file)); setMedia(current => [asset, ...current]); set(mediaField[tab], asset.id); setMessage('Image uploaded. Save this record to publish it.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function uploadAlbumImage(file) { if (!file) return; setBusy(true); try { const asset = unpack(await api.upload(file)); setMedia(current => [asset, ...current]); setImages(current => [...current, { media_id: asset.id, url: asset.url, alt_text: imageAlt || form.title }]); setImageAlt(''); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function removeAlbumImage(asset) { setBusy(true); try { await api.removeImage(asset.id); setExistingImages(current => current.filter(item => item.id !== asset.id)); setMessage('Image removed from album.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function save(event) { event.preventDefault(); setBusy(true); setMessage(''); try { const payload = { ...form }; delete payload.id; delete payload.created_at; delete payload.updated_at; delete payload.deleted_at; delete payload.published_at; delete payload.created_by; delete payload.updated_by; const saved = unpack(await api.save(tab, payload, editing.id)); if (tab === 'gallery' && images.length) await api.addImages(saved.id, images.map(({ media_id, alt_text }) => ({ media_id, alt_text }))); setEditing(null); setMessage(`${tab === 'gallery' ? 'Album' : tab === 'videos' ? 'Video' : 'Notice'} saved successfully.`); await load(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function remove() { setBusy(true); try { await api.remove(tab, deleteTarget.id); setDeleteTarget(null); setMessage('Record removed.'); await load(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  const image = media.find(item => Number(item.id) === Number(form?.[mediaField[tab]]));
  return <div className="admin-module"><InnerPageHeader eyebrow="Website / Announcements" title="Notices, Gallery & Videos" description="Publish announcements, visual stories and videos on the customer website." />
    <div className="account-filters admin-tabs">{Object.keys(defaults).map(type => <button key={type} aria-pressed={tab === type} onClick={() => setTab(type)}>{type}</button>)}</div>
    <section className="admin-data-panel"><header><div><h2>{tab === 'gallery' ? 'Gallery albums' : tab}</h2><p>{items.length} records</p></div><button className="button button--primary" onClick={() => open()}>＋ Add {tab === 'gallery' ? 'album' : tab.slice(0, -1)}</button></header>
      {loading ? <div className="admin-list-loading">Loading…</div> : items.length ? <div className="admin-content-list">{items.map(item => <article key={item.id}><span className="admin-row-index">{String(item.id).padStart(2, '0')}</span><div><strong>{item.title}</strong><small>{item.short_description || item.slug}</small></div><span className={`admin-status admin-status--${item.status}`}>{item.status}</span><div className="admin-crud-actions"><button onClick={() => open(item)}>Edit</button><button className="danger" onClick={() => setDeleteTarget(item)}>Delete</button></div></article>)}</div> : <div className="admin-empty"><h3>No {tab} yet</h3><p>Add the first record to publish it on the website.</p></div>}</section>
    {message && <p className="form-status" role="status">{message}</p>}
    {editing && <div className="admin-modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true"><header><div><small>WEBSITE CONTENT</small><h2>{editing.id ? 'Edit' : 'Add'} {tab === 'gallery' ? 'album' : tab.slice(0, -1)}</h2></div><button onClick={() => setEditing(null)} aria-label="Close">×</button></header><form onSubmit={save}><div className="admin-editor-grid">
      <label><span>Title *</span><input required value={form.title} onChange={event => set('title', event.target.value)} /></label><label><span>Status</span><select value={form.status} onChange={event => set('status', event.target.value)}>{['draft','published','archived'].map(status => <option key={status}>{status}</option>)}</select></label>
      <label className="wide"><span>Summary</span><textarea rows="3" value={form.short_description || ''} onChange={event => set('short_description', event.target.value)} /></label>
      {tab === 'notices' && <><label><span>Notice date *</span><input type="date" required value={form.notice_date?.slice(0, 10) || ''} onChange={event => set('notice_date', event.target.value)} /></label><label><span>External link</span><input type="url" value={form.external_url || ''} onChange={event => set('external_url', event.target.value)} /></label><label className="wide"><span>Notice text</span><textarea rows="7" value={form.content || ''} onChange={event => set('content', event.target.value)} /></label></>}
      {tab === 'gallery' && <><label><span>Event date</span><input type="date" value={form.event_date?.slice(0, 10) || ''} onChange={event => set('event_date', event.target.value)} /></label><label className="wide"><span>Album description</span><textarea rows="5" value={form.description || ''} onChange={event => set('description', event.target.value)} /></label></>}
      {tab === 'videos' && <><label><span>Video platform</span><select value={form.video_type} onChange={event => set('video_type', event.target.value)}>{['youtube','vimeo','external'].map(value => <option key={value}>{value}</option>)}</select></label><label><span>{form.video_type === 'youtube' ? 'YouTube video ID' : form.video_type === 'vimeo' ? 'Vimeo video ID' : 'Video ID'}</span><input value={form.external_video_id || ''} onChange={event => set('external_video_id', event.target.value)} /></label><label className="wide"><span>External URL</span><input type="url" value={form.external_url || ''} onChange={event => set('external_url', event.target.value)} /></label></>}
      <label className="wide"><span>{tab === 'gallery' ? 'Album cover' : tab === 'videos' ? 'Video thumbnail' : 'Featured image'}</span><div className="admin-image-picker">{image?.url && <img src={image.url} alt="Selected media" />}<select value={form[mediaField[tab]] || ''} onChange={event => set(mediaField[tab], event.target.value ? Number(event.target.value) : null)}><option value="">No image selected</option>{media.map(asset => <option key={asset.id} value={asset.id}>{asset.title || asset.original_name}</option>)}</select><input type="file" accept="image/*" onChange={event => upload(event.target.files[0])} /></div></label>
      {tab === 'gallery' && <label className="wide"><span>Add album images</span><input value={imageAlt} onChange={event => setImageAlt(event.target.value)} placeholder="Image description for accessibility" /><input type="file" accept="image/*" onChange={event => uploadAlbumImage(event.target.files[0])} /><div className="admin-gallery-list">{existingImages.map(asset => <div key={asset.id}><img src={asset.media?.url} alt={asset.alt_text} /><button type="button" onClick={() => removeAlbumImage(asset)}>Remove</button></div>)}{images.map(asset => <div key={asset.media_id}><img src={asset.url} alt={asset.alt_text} /><button type="button" onClick={() => setImages(images.filter(value => value.media_id !== asset.media_id))}>Remove</button></div>)}</div></label>}
      <label className="admin-checkbox"><input type="checkbox" checked={Boolean(form.is_featured)} onChange={event => set('is_featured', event.target.checked)} /><span>Featured</span></label>
    </div><footer><button type="button" className="button button--secondary" onClick={() => setEditing(null)}>Cancel</button><button className="button button--primary" disabled={busy}>{busy ? 'Saving…' : 'Save'}</button></footer></form></section></div>}
    {deleteTarget && <div className="admin-modal-backdrop"><section className="admin-confirm" role="alertdialog" aria-modal="true"><h2>Delete {deleteTarget.title}?</h2><p>This will remove it from the public website.</p><div><button className="button button--secondary" onClick={() => setDeleteTarget(null)}>Cancel</button><button className="button admin-delete-button" disabled={busy} onClick={remove}>Delete</button></div></section></div>}
  </div>;
}

