import { useEffect, useState } from 'react';
import { adminService } from '../services/adminService';
import { InnerPageHeader } from '../components/shared/InnerPageComponents';

const metricMeta = {
  users: ['Users', 'Registered accounts', 'U'], articles: ['Articles', 'Knowledge library', 'A'], courses: ['Courses', 'Learning catalogue', 'C'], publications: ['Publications', 'Research journals', 'P'], books: ['Books', 'Store catalogue', 'B'], orders: ['Orders', 'All-time orders', 'O'], self_collect_pending: ['Self Collect', 'Awaiting collection', 'P'], new_enquiries: ['New enquiries', 'Need a response', 'E'], open_tickets: ['Open tickets', 'Support queue', 'T'], career_applications: ['Applications', 'Career submissions', 'J'], notices: ['Notices', 'Published updates', 'N'], referral_signups: ['Referral signups', 'Registered from shared links', 'R'], referral_rewards: ['Referral rewards', 'First paid purchases', '₹'],
};
function DashboardSkeleton() { return <><div className="admin-stat-grid admin-skeleton-grid">{Array.from({ length: 10 }, (_, index) => <article key={index}><i /><i /><b /></article>)}</div><div className="admin-dashboard-columns"><section className="admin-panel admin-skeleton-panel" /><section className="admin-panel admin-skeleton-panel" /></div></>; }

export function AdminLoginPage() {
  const [status, setStatus] = useState('');
  async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); setStatus('Signing in…'); try { const response = await adminService.login(form.get('email'), form.get('password')); sessionStorage.setItem('e4-admin-user', JSON.stringify(response.data.user)); location.replace(new URLSearchParams(location.search).get('redirect') || '/admin'); } catch (error) { setStatus(error.message); } }
  return <div className="admin-login"><form onSubmit={submit}><img src="/brand/e4engineers-logo.png" alt="E4ENGINEERS"/><h1>Administrator Login</h1><p>Manage content, orders, payments and website operations.</p><label>Email<input name="email" type="email" required autoFocus/></label><label>Password<input name="password" type="password" required/></label><button className="button button--primary">Sign in</button>{status&&<p role="status">{status}</p>}<a href="/">Return to website</a></form></div>;
}

export function AdminDashboardPage() {
  const [data, setData] = useState(null), [error, setError] = useState('');
  const [referralAmount,setReferralAmount]=useState('100'),[referralStatus,setReferralStatus]=useState('');
  useEffect(() => { adminService.dashboard().then(response => setData(response.data)).catch(currentError => setError(currentError.message)); }, []);
  useEffect(()=>{adminService.settings().then(response=>setReferralAmount((response.data||[]).find(item=>item.key==='referral_reward_rupees')?.value||'100')).catch(()=>{})},[]);
  async function saveReferralAmount(event){event.preventDefault();if(!/^\d+$/.test(referralAmount)||Number(referralAmount)>10000){setReferralStatus('Enter an amount from ₹0 to ₹10,000.');return}try{await adminService.updateSettings([{key:'referral_reward_rupees',value:referralAmount}]);setReferralStatus('Referral reward saved. New qualifying purchases will use this amount.')}catch(error){setReferralStatus(error.message)}}
  const today = new Intl.DateTimeFormat('en-IN', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date());
  return <div className="admin-dashboard"><section className="admin-welcome"><div><span>CONTROL CENTRE</span><h1>Good to see you.</h1><p>Here is what is happening across E4ENGINEERS today.</p></div><div className="admin-date"><small>TODAY</small><strong>{today}</strong></div></section>
    {error && <div className="admin-error">{error}<button onClick={() => location.reload()}>Retry</button></div>}
    {!data && !error ? <DashboardSkeleton /> : data && <><div className="admin-stat-grid">{Object.entries(data.counts || {}).map(([key, value]) => { const meta = metricMeta[key] || [key.replaceAll('_', ' '), 'Overview', '•']; return <article key={key}><div className={`admin-metric-icon admin-metric-icon--${key}`}>{meta[2]}</div><div><span>{meta[0]}</span><strong>{value}</strong><small>{meta[1]}</small></div></article>; })}</div>
      <div className="admin-dashboard-columns"><section className="admin-panel"><header><div><h2>Recent orders</h2><p>Latest customer purchases</p></div><a href="/admin/orders">View all →</a></header>
        {data.recent_orders?.length ? <div className="admin-order-list">{data.recent_orders.map(order => <a href={`/admin/orders?order=${order.order_number}`} key={order.order_number}><span className="admin-order-mark">#</span><div><strong>{order.order_number}</strong><small>{order.delivery_method==='self_collect'?'Self Collect · ':''}{order.status.replaceAll('_', ' ')} · {order.payment_status.replaceAll('_', ' ')}</small></div><b>{order.currency} {order.grand_total}</b></a>)}</div> : <div className="admin-empty"><span>↗</span><h3>No orders yet</h3><p>New customer orders will appear here automatically.</p><a href="/admin/orders">Open order management</a></div>}
      </section><section className="admin-panel"><header><div><h2>Referral rewards</h2><p>₹{data.referral_credit_issued_rupees} store credit issued</p></div></header><form onSubmit={saveReferralAmount} className="admin-toolbar"><label><span>Reward per first paid purchase (₹)</span><input type="number" min="0" max="10000" step="1" value={referralAmount} onChange={event=>setReferralAmount(event.target.value)}/></label><button className="button button--primary">Save reward</button></form>{referralStatus&&<p role="status">{referralStatus}</p>}{data.recent_referrals?.length?<div className="admin-order-list">{data.recent_referrals.map((entry,index)=><div key={index}><strong>{entry.referrer}</strong><small> referred {entry.buyer}</small><b> +₹{(entry.amount_paise/100).toFixed(2)}</b></div>)}</div>:<div className="admin-empty"><h3>No rewarded referrals yet</h3><p>First verified purchases from referred customers will appear here.</p></div>}</section><section className="admin-panel"><header><div><h2>Quick actions</h2><p>Common administration tasks</p></div></header><div className="admin-quick-actions">
        <a href="/admin/books"><span>＋</span><div><strong>Add a book</strong><small>Set cover, price and stock</small></div></a><a href="/admin/publishing"><span>✎</span><div><strong>Publish content</strong><small>Write articles and manage learning</small></div></a><a href="/admin/orders"><span>⌕</span><div><strong>Review orders</strong><small>Manage fulfilment and status</small></div></a><a href="/admin/payments"><span>₹</span><div><strong>Payment settings</strong><small>Configure payment gateways</small></div></a><a href="/admin/discovery"><span>◫</span><div><strong>Publish an update</strong><small>Add notices, gallery or video</small></div></a>
      </div></section></div></>}
  </div>;
}

const modules=['pages','articles','courses','publications','resources','books','contributors','banners','media'];
export function AdminContentPage(){const[type,setType]=useState('pages'),[items,setItems]=useState([]),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState('');useEffect(()=>{setLoading(true);setMessage('');adminService.content(type).then(r=>setItems(r.data?.data||r.data||[])).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[type]);const visible=items.filter(x=>(x.title||x.name||x.original_name||'').toLowerCase().includes(query.toLowerCase()));return <div className="admin-module"><InnerPageHeader eyebrow="Content management" title="Website Content" description="Review, organize and manage everything published across E4ENGINEERS."/><div className="admin-module-summary"><div><strong>{items.length}</strong><span>{type} records</span></div><label><span>Search current section</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${type}...`}/></label></div><div className="account-filters admin-tabs">{modules.map(x=><button aria-pressed={type===x} onClick={()=>{setType(x);setQuery('')}} key={x}>{x}</button>)}</div><section className="account-section admin-data-panel"><header><div><h2>{type}</h2><p>Manage titles, publishing status and content details.</p></div><span className="admin-status admin-status--published">{visible.length} records</span></header>{loading?<div className="admin-list-loading">Loading {type}…</div>:visible.length?<div className="admin-content-list">{visible.map((x,index)=>{const title=x.title||x.name||x.original_name;const status=x.status||'published';return <article key={x.id}><span className="admin-row-index">{String(index+1).padStart(2,'0')}</span><div><strong>{title}</strong><small>{x.slug||x.mime_type||`${type} content`}</small></div><span className={`admin-status admin-status--${status}`}>{status}</span></article>})}</div>:<div className="admin-empty"><span>⌕</span><h3>No {type} found</h3><p>{query?'Try another search term.':`New ${type} will appear here.`}</p></div>}</section>{message&&<p className="form-status">{message}</p>}</div>}
export function AdminOrdersPage(){const[orders,setOrders]=useState([]),[search,setSearch]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);async function load(){setLoading(true);try{const r=await adminService.orders({search,per_page:50});setOrders(r.data||[])}catch(e){setMessage(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);async function update(order,status){try{await adminService.updateOrder(order.order_number,status);setMessage('Order updated.');load()}catch(e){setMessage(e.message)}}async function collectCod(order){if(!window.confirm(`Confirm cash was collected for ${order.order_number}?`))return;try{await adminService.collectCod(order.order_number);setMessage('COD collection confirmed.');load()}catch(error){setMessage(error.message)}}return <div className="admin-module"><InnerPageHeader eyebrow="Commerce" title="Order Management" description="Search, review and control customer order fulfilment."/><form className="admin-toolbar" onSubmit={e=>{e.preventDefault();load()}}><label><span>Search orders</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Order number, customer or email"/></label><button className="button button--primary">Search</button></form><section className="account-section admin-data-panel"><header><div><h2>All orders</h2><p>{orders.length} orders in the current view</p></div></header>{loading?<div className="admin-list-loading">Loading orders…</div>:orders.length?<div className="admin-order-table">{orders.map(o=><article key={o.order_number}><div><strong>{o.order_number}</strong><small>{o.shipping_address?.name||'Customer'}</small></div><div><small>Order total</small><strong>{o.currency} {o.pricing?.total}</strong></div><span className={`admin-status admin-status--${o.payment_status}`}>{o.payment_status}</span><select value={o.status} onChange={e=>update(o,e.target.value)}>{['payment_pending','confirmed','processing','packed','shipped','delivered','cancelled'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select>{o.payment_method==='cod'&&o.status==='delivered'&&o.payment_status==='cod_pending'&&<button type="button" onClick={()=>collectCod(o)}>Mark COD collected</button>}</article>)}</div>:<div className="admin-empty"><span>□</span><h3>No orders found</h3><p>Orders matching your search will appear here.</p></div>}</section>{message&&<p className="form-status">{message}</p>}</div>}

