import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BookOpen, CheckCircle, Envelope, FileText, MagnifyingGlass, MapPin, Phone, ShoppingCart } from "@phosphor-icons/react";
import { Breadcrumb, EmptyState, InnerPageHeader, InnerSection, Pagination } from "../components/shared/InnerPageComponents";
import { AccessBadge, FilterBar, FilterField, ResourceCard } from "../components/shared/PhaseTwoComponents";
import { BookCard, QuantitySelector, StockBadge } from "../components/shared/PhaseThreeComponents";
import { disciplines } from "../data/phaseOneData";
const articles = [];
import { courses, publications, studyResources } from "../data/phaseTwoData";
import { booksCatalog, contactInfo } from "../data/phaseThreeData";
import { useCart } from "../state/CartContext";
import { operationsService } from "../services/operationsService";
import { discoveryService } from "../services/discoveryService";

const Page=({children})=><div className="inner-page"><div className="container inner-page__container">{children}</div></div>;
const disciplineOptions=<><option>All Disciplines</option>{disciplines.map(d=><option key={d.slug}>{d.name}</option>)}</>;

export function ResourceDetailPage({slug}){const resource=studyResources.find(x=>x.slug===slug)||studyResources[1];const premium=resource.access==="Premium";return <Page><Breadcrumb items={[{label:"Home",href:"/"},{label:"Study Resources",href:"/resources"},{label:resource.title}]}/><div className="resource-detail-header"><div className="resource-document"><FileText aria-hidden="true"/><span>{resource.format}</span></div><div><p>{resource.type} · {resource.discipline}</p><h1>{resource.title}</h1><span>{resource.description}</span><AccessBadge type={resource.access}/><button className="button button--primary" type="button">{premium?"Login / Purchase required":"Access Resource"} <ArrowRight/></button></div></div><dl className="resource-meta">{[["Resource Type",resource.type],["Discipline",resource.discipline],["Access",resource.access],["Format",resource.format],["Pages",resource.pages],["Updated",resource.updated],["Language",resource.language]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><InnerSection title="About this Resource"><p className="section-copy">A concise engineering reference designed for focused study, classroom support and quick revision. It organises essential material into a clear, practical format.</p></InnerSection><InnerSection title="Topics Covered"><ul className="topic-grid">{["Core formulas","Engineering applications","Reference equations","Important concepts","Quick revision topics"].map(x=><li key={x}><CheckCircle weight="fill"/>{x}</li>)}</ul></InnerSection><InnerSection title="Resource Preview"><div className="document-preview"><FileText/><div><h3>Sample page preview</h3><p>Representative headings, equations and reference notes demonstrate the resource structure. No protected file or paid download is exposed.</p></div></div></InnerSection><InnerSection title="Related Resources"><div className="resource-list-grid">{studyResources.filter(x=>x.id!==resource.id).slice(0,4).map(x=><ResourceCard resource={x} key={x.id}/>)}</div></InnerSection><a className="discipline-back-link" href={`/engineering/${resource.discipline.toLowerCase().replaceAll(" ","-")}`}>Explore {resource.discipline} <ArrowRight/></a></Page>}

export function BooksPage(){const{addItem}=useCart();const[q,setQ]=useState("");const[d,setD]=useState("All Disciplines");const[stock,setStock]=useState("All");const[sort,setSort]=useState("Latest");const[notice,setNotice]=useState("");const filtered=useMemo(()=>{let list=booksCatalog.filter(x=>(d==="All Disciplines"||x.discipline===d)&&(stock==="All"||x.stock===stock)&&`${x.title} ${x.author}`.toLowerCase().includes(q.toLowerCase()));if(sort==="A–Z")list=[...list].sort((a,b)=>a.title.localeCompare(b.title));if(sort==="Price: Low to High")list=[...list].sort((a,b)=>a.price-b.price);if(sort==="Price: High to Low")list=[...list].sort((a,b)=>b.price-a.price);return list},[q,d,stock,sort]);return <Page><Breadcrumb items={[{label:"Home",href:"/"},{label:"Books"}]}/><InnerPageHeader eyebrow="Engineering bookshop" title="Engineering Book Catalogue" description="Explore engineering books for academic learning, technical reference and professional development."/><FilterBar><FilterField label="Search books" className="catalog-search"><input placeholder="Search books..." value={q} onChange={e=>setQ(e.target.value)}/></FilterField><FilterField label="Engineering Discipline"><select value={d} onChange={e=>setD(e.target.value)}>{disciplineOptions}</select></FilterField><FilterField label="Category"><select><option>All Categories</option><option>Academic Textbook</option><option>Reference</option></select></FilterField><FilterField label="Availability"><select value={stock} onChange={e=>setStock(e.target.value)}><option>All</option><option>In Stock</option><option>Out of Stock</option></select></FilterField><FilterField label="Sort By"><select value={sort} onChange={e=>setSort(e.target.value)}><option>Latest</option><option>Popular</option><option>Price: Low to High</option><option>Price: High to Low</option><option>A–Z</option></select></FilterField></FilterBar>{notice&&<p className="prototype-notice" role="status">{notice}</p>}{filtered.length?<><div className="books-list-grid">{filtered.map(x=><BookCard book={x} onAddToCart={b=>{addItem(b);setNotice(`${b.title} added to cart.`)}} key={x.slug}/>)}</div><Pagination/></>:<EmptyState title="No books found" message="Try changing your search or filters."/>}</Page>}

export function BookDetailPage({slug}){const{addItem}=useCart();const book=booksCatalog.find(x=>x.slug===slug)||booksCatalog[0];const[qty,setQty]=useState(1);const[notice,setNotice]=useState("");const[pin,setPin]=useState("");return <Page><Breadcrumb items={[{label:"Home",href:"/"},{label:"Books",href:"/books"},{label:book.title}]}/><div className="book-detail"><div className="book-gallery"><img src={book.image} alt={`${book.title} cover`}/><p>Engineering academic edition</p></div><div className="book-info"><small>{book.discipline}</small><h1>{book.title}</h1><p className="book-author">by {book.author}</p><dl>{[["Publisher",book.publisher],["Edition",book.edition],["ISBN",book.isbn]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><StockBadge stock={book.stock}/><div className="book-detail-price"><strong>₹{book.price}</strong><del>₹{book.mrp}</del><span>Save ₹{book.mrp-book.price}</span></div><label className="quantity-label">Quantity<QuantitySelector value={qty} onChange={setQty}/></label><div className="product-actions"><button className="button button--primary" type="button" onClick={()=>{addItem(book,qty);setNotice(`${qty} × ${book.title} added to cart.`)}} disabled={book.stock==="Out of Stock"}><ShoppingCart/> Add to Cart</button><button className="button button--secondary" type="button" onClick={()=>setNotice("Buy Now will connect to login and checkout in a future phase.")}>Buy Now</button></div>{notice&&<p className="prototype-notice" role="status">{notice}</p>}<form className="delivery-check" onSubmit={e=>{e.preventDefault();setNotice("Delivery availability will be confirmed at checkout.")}}><label>Check Delivery Availability<input inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="Enter PIN Code"/></label><button type="submit">Check</button></form></div></div><InnerSection title="About this Book"><p className="section-copy">A comprehensive engineering text combining clear theory, worked examples and practical system perspectives for academic study and professional reference.</p></InnerSection><InnerSection title="Book Details"><dl className="publication-details">{[["Author",book.author],["Publisher",book.publisher],["Edition",book.edition],["ISBN",book.isbn],["Language","English"],["Pages",book.pages],["Discipline",book.discipline],["Format",book.format]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></InnerSection><InnerSection title="What You Will Learn"><ul className="topic-grid">{["Generation fundamentals","Transmission systems","Distribution systems","Power flow concepts","Protection","System economics"].map(x=><li key={x}><CheckCircle weight="fill"/>{x}</li>)}</ul></InnerSection><InnerSection title="Related Books"><div className="books-list-grid">{booksCatalog.filter(x=>x.slug!==book.slug).slice(0,4).map(x=><BookCard book={x} onAddToCart={b=>{addItem(b);setNotice(`${b.title} added to cart.`)}} key={x.slug}/>)}</div></InnerSection></Page>}

const searchable=()=>[
 ...articles.map(x=>({type:"Articles",title:x.title,description:x.excerpt,href:`/articles/${x.slug}`,meta:x.discipline})),
 ...courses.map(x=>({type:"Courses",title:x.title,description:x.description,href:`/courses/${x.slug}`,meta:x.discipline})),
 ...booksCatalog.map(x=>({type:"Books",title:x.title,description:`Engineering book by ${x.author}.`,href:`/books/${x.slug}`,meta:x.discipline})),
 ...publications.map(x=>({type:"Publications",title:x.title,description:`${x.type}, ${x.issue}.`,href:`/publications/${x.slug}`,meta:x.discipline})),
 ...studyResources.map(x=>({type:"Resources",title:x.title,description:x.description,href:`/resources/${x.slug}`,meta:x.discipline})),
 ...disciplines.map(x=>({type:"Engineering",title:x.name,description:x.description,href:`/engineering/${x.slug}`,meta:"Engineering discipline"})),
];
export function SearchPage(){const initial=new URLSearchParams(window.location.search).get("q")||"";const[q,setQ]=useState(initial),[submitted,setSubmitted]=useState(initial),[type,setType]=useState(""),[items,setItems]=useState([]),[meta,setMeta]=useState({}),[loading,setLoading]=useState(false);useEffect(()=>{if(submitted.length<2){setItems([]);return}setLoading(true);discoveryService.search({q:submitted,type,per_page:20}).then(r=>{setItems(r.data||[]);setMeta(r.meta||{})}).finally(()=>setLoading(false))},[submitted,type]);function submit(e){e.preventDefault();setSubmitted(q.trim());history.replaceState({},"",`/search?q=${encodeURIComponent(q.trim())}`)}return <Page><Breadcrumb items={[{label:"Home",href:"/"},{label:"Search"}]}/><InnerPageHeader eyebrow="Search across the platform" title="Search E4ENGINEERS" description="Find public engineering knowledge across articles, courses, books, publications, resources and updates."/><form className="universal-search" onSubmit={submit}><MagnifyingGlass/><input aria-label="Search E4ENGINEERS" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search E4ENGINEERS..."/><button type="submit">Search</button></form><div className="catalog-tabs">{[["","All"],["article","Articles"],["course","Courses"],["book","Books"],["publication","Publications"],["resource","Resources"],["notice","Notices"],["video","Videos"]].map(([value,label])=><button type="button" aria-pressed={type===value} onClick={()=>setType(value)} key={label}>{label}</button>)}</div>{submitted&&<p className="search-summary">Search results for <strong>“{submitted}”</strong> · {meta.total||0} results found</p>}{loading?<p role="status">Searching…</p>:items.length?<div className="search-groups">{items.map(item=><article className="search-result" key={`${item.type}-${item.url}`}><div><small>{item.type}</small><h3>{item.title}</h3><p>{item.description}</p></div><a href={item.url}>View <ArrowRight/></a></article>)}</div>:<EmptyState title={`No results found for “${submitted}”`} message="Try a different keyword."/>}</Page>}
export function ContactPage(){const[status,setStatus]=useState("");async function submit(e){e.preventDefault();const element=e.currentTarget;const form=new FormData(element);const required=["name","email","subject","message"];const missing=required.filter(x=>!String(form.get(x)||"").trim());const mobile=String(form.get("mobile")||"");if(missing.length){setStatus("Please complete all required fields.");return}if(mobile&&!/^\d{10}$/.test(mobile)){setStatus("Enter a valid 10-digit mobile number.");return}setStatus("Sending…");try{const typeMap={"General Enquiry":"general","Course Enquiry":"content","Book Enquiry":"content","Publication Enquiry":"content","Study Resource Enquiry":"content","Technical Assistance":"technical"};await operationsService.contact({name:form.get("name"),email:form.get("email"),mobile,subject:form.get("subject"),message:form.get("message"),type:typeMap[form.get("type")]||"general",website:form.get("website")||""});element.reset();setStatus("Thank you. Your enquiry has been received.")}catch(error){setStatus(error.message)}}const icons=[Envelope,Phone,MapPin,BookOpen];return <Page><Breadcrumb items={[{label:"Home",href:"/"},{label:"Contact"}]}/><InnerPageHeader eyebrow="We are here to help" title="Contact E4ENGINEERS" description="Have a question about courses, resources, publications or engineering books? Get in touch with us."/><div className="contact-layout"><aside className="contact-info"><h2>Contact information</h2>{contactInfo.map(([a,b],i)=>{const Icon=icons[i];return <div key={a}><Icon/><span><strong>{a}</strong>{b}</span></div>})}</aside><form className="contact-form" onSubmit={submit} noValidate><div className="form-grid"><input className="form-honeypot" name="website" tabIndex="-1" autoComplete="off" aria-hidden="true"/><label>Full Name *<input name="name" required/></label><label>Email *<input name="email" type="email" required/></label><label>Mobile<input name="mobile" inputMode="numeric"/></label><label>Enquiry Type<select name="type"><option>General Enquiry</option><option>Course Enquiry</option><option>Book Enquiry</option><option>Publication Enquiry</option><option>Study Resource Enquiry</option><option>Technical Assistance</option></select></label><label className="form-wide">Subject *<input name="subject" required/></label><label className="form-wide">Message *<textarea name="message" rows="6" required/></label></div><button className="button button--primary" type="submit">Send Enquiry <ArrowRight/></button>{status&&<p className="form-status" role="status">{status}</p>}</form></div></Page>}



