import{shippingService}from'../services/shippingService.js';import{invoiceService}from'../services/invoiceService.js';
import{useEffect,useState}from"react";import{ArrowRight,CheckCircle,MapPin,Package,PencilSimple,Plus,Trash}from"@phosphor-icons/react";import{AccountLayout,OrderSummary,ProtectedRoute}from"../components/shared/AccountComponents";import{Breadcrumb,InnerPageHeader}from"../components/shared/InnerPageComponents";import{checkoutService}from"../services/checkoutService";import{paymentService}from"../services/paymentService.js";import{useCart}from"../state/CartContext";import{useCustomer}from"../state/CustomerContext";import{useAuth}from"../state/AuthContext.jsx";
const Page=({children})=><div className="inner-page"><div className="container inner-page__container">{children}</div></div>;
const addressFields=[['name','Full Name'],['mobile','Mobile Number'],['line1','Address Line 1'],['line2','Address Line 2'],['landmark','Landmark'],['city','City'],['state','State'],['pin','PIN Code']];
function AddressForm({initial,onSave,onCancel}){const[data,setData]=useState(initial||{type:"Home",name:"",mobile:"",line1:"",line2:"",landmark:"",city:"",state:"",pin:"",isDefault:false});const[error,setError]=useState("");function submit(e){e.preventDefault();if(!data.name||!/^\d{10}$/.test(data.mobile)||!data.line1||!data.city||!data.state||!/^\d{6}$/.test(data.pin)){setError("Complete all required fields with a valid mobile number and PIN code.");return}onSave(data)}return <form className="address-form" onSubmit={submit} noValidate><div>{addressFields.map(([name,label])=><label key={name}>{label}{!['line2','landmark'].includes(name)&&' *'}<input value={data[name]} inputMode={name==='mobile'||name==='pin'?'numeric':undefined} onChange={e=>setData({...data,[name]:e.target.value})}/></label>)}<label>Address Type<select value={data.type} onChange={e=>setData({...data,type:e.target.value})}><option>Home</option><option>Office</option><option>Other</option></select></label><label className="checkbox-field"><input type="checkbox" checked={data.isDefault} onChange={e=>setData({...data,isDefault:e.target.checked})}/> Set as Default</label></div>{error&&<p className="field-error" role="alert">{error}</p>}<footer><button className="button button--primary" type="submit">Save Address</button>{onCancel&&<button className="button button--secondary" type="button" onClick={onCancel}>Cancel</button>}</footer></form>}
function AddressCard({address,selected,onSelect,onEdit,onDelete,onDefault}){return <article className={`address-card ${selected?'selected':''}`}><label><input type="radio" name="address" checked={selected} onChange={()=>onSelect?.(address.id)}/><span><strong>{address.type}</strong>{address.isDefault&&<small>Default</small>}</span></label><h3>{address.name}</h3><p>{address.line1}{address.line2&&`, ${address.line2}`}<br/>{address.city}, {address.state} — {address.pin}<br/>{address.mobile}</p>{onEdit&&<div><button onClick={()=>onEdit(address)}><PencilSimple/>Edit</button><button onClick={()=>onDelete(address.id)}><Trash/>Delete</button>{!address.isDefault&&<button onClick={()=>onDefault(address.id)}>Set Default</button>}</div>}</article>}
export function CheckoutPage(){
  const{items,subtotal,coupon,couponDiscount,discountedSubtotal,refresh}=useCart();const{user,isAuthenticated,refreshUser}=useAuth();const{addresses}=useCustomer();
  const blank={type:"home",full_name:"",mobile:"",address_line_1:"",address_line_2:"",landmark:"",city:"",state:"",postal_code:"",country_code:"IN"};
  const[contact,setContact]=useState({name:user?.name||"",email:user?.email||"",mobile:user?.mobile||""});const[address,setAddress]=useState(blank);const[selected,setSelected]=useState(addresses.find(x=>x.isDefault)?.id||addresses[0]?.id||null);
  const[terms,setTerms]=useState(false);const[shipping,setShipping]=useState(null);const[status,setStatus]=useState("");const[loading,setLoading]=useState(false);const[methods,setMethods]=useState({cod:{enabled:true},online:[]});const[payment,setPayment]=useState("cod");const[scanProof,setScanProof]=useState(null);const[scanReference,setScanReference]=useState("");
  const[creditBalance,setCreditBalance]=useState(0);const[useCredit,setUseCredit]=useState(false);
  useEffect(()=>{if(isAuthenticated)checkoutService.accountDashboard().then(r=>setCreditBalance(Number(r.data?.referral?.store_credit_rupees||0))).catch(()=>setCreditBalance(0))},[isAuthenticated]);
  useEffect(()=>{if(user)setContact({name:user.name||"",email:user.email||"",mobile:user.mobile||""})},[user]);useEffect(()=>{paymentService.methods().then(r=>{setMethods(r.data);if(!r.data.cod?.enabled)setPayment(r.data.scanpay?.enabled?"scanpay":r.data.online?.[0]?.code?.toLowerCase()||"cod")}).catch(()=>{})},[]);
  async function quote(){const saved=addresses.find(x=>x.id===selected);const postal=saved?.pin||address.postal_code;if(!/^[1-9]\d{5}$/.test(postal)){setStatus("Enter a valid 6-digit PIN code.");return}setLoading(true);try{const r=isAuthenticated&&selected?await shippingService.checkoutOptions({addressId:selected,paymentMode:payment==="cod"?"cod":"prepaid"}):await shippingService.cartQuote({postalCode:postal,paymentMode:payment==="cod"?"cod":"prepaid"});setShipping(r.data);setStatus("")}catch(e){setShipping(null);setStatus(e.message)}finally{setLoading(false)}}
  async function place(){if(!terms||!shipping?.selected_quote){setStatus("Confirm shipping and accept the policies before placing your order.");return}if(payment==="scanpay"&&(!scanProof||!/^image\/(png|jpeg|webp)$/.test(scanProof.type)||scanProof.size>5*1024*1024)){setStatus("Upload a PNG, JPG or WebP payment screenshot under 5 MB.");return}setLoading(true);try{let key=sessionStorage.getItem("e4engineers-checkout-key");if(!key){key=crypto.randomUUID();sessionStorage.setItem("e4engineers-checkout-key",key)}const body={contact,shipping_quote_id:shipping.selected_quote.quote_id,payment_method:payment,idempotency_key:key,use_store_credit:isAuthenticated&&useCredit,...(isAuthenticated&&selected?{address_id:selected}:{shipping_address:address})};const r=await checkoutService.placeOrder(body);const order=r.data.order;checkoutService.saveAccess(order.order_number,r.data.order_access_token);if(payment==="scanpay")await paymentService.submitScanProof(order.order_number,scanProof,scanReference);if(r.data.payment?.client_action){await paymentService.perform(r.data.payment.client_action,async payload=>{await paymentService.verify(order.order_number,r.data.payment.attempt_id,payload);location.href=`/order-success/${encodeURIComponent(order.order_number)}`})}sessionStorage.removeItem("e4engineers-checkout-key");localStorage.removeItem("e4engineers-guest-cart-token");await refresh();if(r.data.account_created)await refreshUser();location.href=`/order-success/${encodeURIComponent(order.order_number)}`}catch(e){setStatus(e.message);setLoading(false)}}
  if(!items.length)return <Page><Breadcrumb items={[{label:"Home",href:"/"},{label:"Cart",href:"/cart"},{label:"Checkout"}]}/><div className="empty-cart"><Package/><h2>Your cart is empty.</h2><p>Add engineering books before starting checkout.</p><a className="button button--primary" href="/books">Browse Books <ArrowRight/></a></div></Page>;
  return <Page><Breadcrumb items={[{label:"Home",href:"/"},{label:"Cart",href:"/cart"},{label:"Checkout"}]}/><InnerPageHeader eyebrow="Secure checkout" title="Checkout" description="Place your order in one step. No registration or password is required."/><div className="checkout-layout"><div className="checkout-sections">
  <section><h2><span>1</span>Contact Information</h2>{!isAuthenticated?<div className="address-form"><div>{[["name","Full Name","text"],["email","Email Address","email"],["mobile","Mobile Number","tel"]].map(([key,label,type])=><label key={key}>{label} *<input type={type} autoComplete={key==="name"?"name":key} value={contact[key]} onChange={e=>setContact({...contact,[key]:e.target.value})}/></label>)}</div><small>An account will be created after your order. You will receive a secure password setup link.</small></div>:<div className="contact-review"><strong>{contact.name}</strong><span>{contact.email}</span><span>{contact.mobile}</span></div>}</section>
  <section><h2><span>2</span>Delivery Address</h2>{isAuthenticated&&addresses.length>0?<div className="address-grid">{addresses.map(x=><AddressCard address={x} selected={selected===x.id} onSelect={setSelected} key={x.id}/>)}</div>:<div className="address-form"><div>{[["full_name","Full Name"],["mobile","Mobile Number"],["address_line_1","Address Line 1"],["address_line_2","Address Line 2"],["landmark","Landmark"],["city","City"],["state","State"],["postal_code","PIN Code"]].map(([key,label])=><label key={key}>{label}{!["address_line_2","landmark"].includes(key)&&" *"}<input autoComplete={key==="postal_code"?"postal-code":"shipping "+key.replaceAll("_","-")} value={address[key]} onChange={e=>setAddress({...address,[key]:e.target.value})}/></label>)}</div></div>}</section>
  <section><h2><span>3</span>Delivery Method</h2><button className="button button--secondary" type="button" disabled={loading} onClick={quote}>{loading?"Checking…":"Calculate shipping"}</button>{shipping?.selected_quote&&<div className="contact-review"><strong>{shipping.selected_quote.courier_name}</strong><span>₹{shipping.selected_quote.shipping_charge} · Estimated {shipping.selected_quote.estimated_delivery||"after dispatch"}</span></div>}</section>
  <section><h2><span>4</span>Payment Method</h2><div className="payment-methods">{methods.cod?.enabled&&<label className={payment==="cod"?"selected":""}><input type="radio" name="payment" checked={payment==="cod"} onChange={()=>{setPayment("cod");setShipping(null)}}/><strong>Cash on Delivery</strong><small>Pay when your order arrives.</small></label>}{methods.scanpay?.enabled&&<label className={payment==="scanpay"?"selected":""}><input type="radio" name="payment" checked={payment==="scanpay"} onChange={()=>{setPayment("scanpay");setShipping(null)}}/><strong>Scan & Pay</strong><small>Scan the QR code and upload your payment screenshot.</small></label>}{methods.online?.map(x=><label className={payment===x.code.toLowerCase()?"selected":""} key={x.code}><input type="radio" name="payment" checked={payment===x.code.toLowerCase()} onChange={()=>{setPayment(x.code.toLowerCase());setShipping(null)}}/><strong>{x.name}</strong><small>Secure {x.is_default?"recommended ":""}online payment.</small></label>)}</div>{payment==="scanpay"&&methods.scanpay?.enabled&&<div className="scan-payment-panel"><img src={methods.scanpay.qr_url} alt={`Scan and pay ${methods.scanpay.payee_name} via UPI`} /><div><strong>Scan this code with your UPI app</strong><p>Pay the exact total shown in your order summary to {methods.scanpay.payee_name} ({methods.scanpay.upi_id}). Your order stays pending until we verify the payment.</p><label>Payment screenshot *<input type="file" accept="image/png,image/jpeg,image/webp" required onChange={event=>setScanProof(event.target.files?.[0]||null)}/></label><label>UPI transaction reference (optional)<input type="text" maxLength="100" value={scanReference} onChange={event=>setScanReference(event.target.value)} placeholder="Enter UTR or transaction ID"/></label></div></div>}</section>
  <section><h2><span>5</span>Review & Place Order</h2>{isAuthenticated&&creditBalance>0&&<label className="policy-check"><input type="checkbox" checked={useCredit} onChange={e=>setUseCredit(e.target.checked)}/><span>Use my ₹{creditBalance.toFixed(2)} store credit on this order</span></label>}{useCredit&&<p>Available credit is applied up to the payable amount; at least ₹1 remains for the selected payment method. Final amount appears on the order confirmation.</p>}<label className="policy-check"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>I agree to the <a href="/terms">Terms of Use</a>, <a href="/shipping-policy">Shipping Policy</a> and <a href="/returns-refunds">Returns & Refunds Policy</a>.</span></label><button className="button button--primary" disabled={loading||!terms||!shipping?.selected_quote} onClick={place}>{loading?"Placing order…":payment==="cod"?"Place COD Order":payment==="scanpay"?"Submit Payment for Verification":"Continue to Secure Payment"} <ArrowRight/></button>{status&&<p className="form-status" role="alert">{status}</p>}</section></div><OrderSummary items={items} subtotal={subtotal} coupon={coupon} couponDiscount={couponDiscount} discountedSubtotal={discountedSubtotal} shipping={shipping?.selected_quote} payment={payment==="cod"?"Cash on Delivery":payment==="scanpay"?"Scan & Pay":payment.toUpperCase()} useCredit={useCredit} creditBalance={creditBalance}/></div></Page>
}
export function OrderSuccessPage({orderNumber}){const[order,setOrder]=useState(null);const[error,setError]=useState("");useEffect(()=>{checkoutService.orderSuccess(orderNumber,checkoutService.readAccess(orderNumber)).then(r=>setOrder(r.data)).catch(e=>setError(e.message))},[orderNumber]);if(error)return <Page><div className="empty-cart"><Package/><h2>Order confirmation unavailable.</h2><p>{error}</p><a className="button button--primary" href="/account/orders">My Orders</a></div></Page>;if(!order)return <Page><p>Loading order confirmation…</p></Page>;const a=order.shipping_address;return <Page><Breadcrumb items={[{label:"Home",href:"/"},{label:"Order Confirmation"}]}/><div className="order-success"><CheckCircle weight="fill"/><h1>{order.payment_method==="scanpay"&&order.payment_status!=="paid"?"Payment submitted for verification":"Order placed successfully"}</h1><p>{order.payment_method==="scanpay"&&order.payment_status!=="paid"?"Your screenshot is awaiting manual review. We will confirm the order after payment verification.":"Your order is confirmed and its invoice is ready."}</p><strong>Order Number: {order.order_number}</strong></div><div className="confirmation-grid"><section className="confirmation-details"><h2>Order Summary</h2>{order.items.map(x=><p key={x.book_id}>{x.title} × {x.quantity} — ₹{x.line_total}</p>)}<strong>Total: ₹{order.pricing.total}</strong></section><section className="confirmation-details"><h2>Delivery Address</h2><p>{a.name}<br/>{a.address_line_1}<br/>{a.city}, {a.state} — {a.postal_code}</p><h2>Order Status</h2><p>{order.status}</p><h2>Payment Status</h2><p>{order.payment_status}</p></section></div><div className="success-actions">{(order.payment_method!=="scanpay"||order.payment_status==="paid")&&<button className="button button--secondary" onClick={()=>invoiceService.download(order.order_number)}>Download Invoice</button>}<a className="button button--secondary" href={`/account/orders/${order.order_number}`}>View Order</a><a className="button button--primary" href="/books">Continue Shopping</a></div></Page>}
export function AccountPage(){
  const {user}=useAuth();
  const [dashboard,setDashboard]=useState(null);
  const [error,setError]=useState('');
  const [copied,setCopied]=useState(false);
  useEffect(()=>{
    if(!user?.id){setDashboard(null);return;}
    let active=true;
    setDashboard(null);
    checkoutService.accountDashboard().then(response=>{if(active){setDashboard(response.data);setError('');}}).catch(currentError=>{if(active)setError(currentError.message);});
    return()=>{active=false;};
  },[user?.id]);
  const stats=[['Total Orders',dashboard?.total_orders],['Orders in Progress',dashboard?.orders_in_progress],['Delivered Orders',dashboard?.delivered_orders],['Digital Resources',dashboard?.digital_resources]];
  return <ProtectedRoute><Page><Breadcrumb items={[{label:'Home',href:'/'},{label:'My Account'}]}/><AccountLayout title={`Hello, ${user?.name||'Customer'}`} description="Manage your orders, account information and purchased resources from one place.">
    {error&&<p className="form-status" role="alert">{error}</p>}
    <div className="account-stats">{stats.map(([label,value])=><article key={label}><strong>{dashboard?value:'—'}</strong><span>{label}</span></article>)}</div>
    {dashboard?.referral&&<section className="account-section referral-panel"><h2>Invite friends & earn store credit</h2><p>Share your link. When a friend registers and completes their first verified paid order, you earn ₹{dashboard.referral.reward_amount_rupees} store credit.</p><label>Your referral link<input readOnly value={`${location.origin}/register?ref=${dashboard.referral.code}`} onFocus={event=>event.target.select()}/></label><button className="button button--secondary" type="button" onClick={async()=>{await navigator.clipboard.writeText(`${location.origin}/register?ref=${dashboard.referral.code}`);setCopied(true)}}>{copied?'Copied':'Copy referral link'}</button><div className="account-stats"><article><strong>{dashboard.referral.registered}</strong><span>Registered friends</span></article><article><strong>{dashboard.referral.rewarded}</strong><span>Rewarded purchases</span></article><article><strong>₹{dashboard.referral.store_credit_rupees}</strong><span>Store credit balance</span></article></div>{dashboard.referral.rewards?.length>0&&<div className="orders-table">{dashboard.referral.rewards.map((reward,index)=><div key={index}><span>{reward.name}</span><span>{new Date(reward.credited_at).toLocaleDateString('en-IN')}</span><strong>+₹{(reward.amount_paise/100).toFixed(2)}</strong></div>)}</div>}</section>}
    <section className="account-section"><h2>Recent Orders</h2>{dashboard?.recent_orders?.length?<div className="orders-table">{dashboard.recent_orders.map(order=><div key={order.order_number}><span>{order.order_number}</span><span>{new Date(order.placed_at).toLocaleDateString('en-IN')}</span><span>₹{order.pricing.total}</span><span>{order.status.replaceAll('_',' ')}</span><a href={`/account/orders/${encodeURIComponent(order.order_number)}`}>View</a></div>)}</div>:!error&&<p>{dashboard?'No orders yet. Your purchases will appear here.':'Loading your orders…'}</p>}</section>
    <section className="account-section"><h2>Quick Actions</h2><div className="quick-actions"><a href="/books">Browse Books</a><a href={dashboard?.recent_orders?.[0]?`/account/orders/${encodeURIComponent(dashboard.recent_orders[0].order_number)}/track`:'/account/orders'}>{dashboard?.recent_orders?.length?'Track Latest Order':'My Orders'}</a><a href="/account/downloads">View Downloads</a><a href="/account/addresses">My Addresses</a></div></section>
  </AccountLayout></Page></ProtectedRoute>;
}
export function ProfilePage(){const{profile,updateProfile}=useCustomer();const[editing,setEditing]=useState(false);const[data,setData]=useState(profile);const[status,setStatus]=useState("");useEffect(()=>setData(profile),[profile]);async function save(){if(!data.name||!/^\S+@\S+\.\S+$/.test(data.email)||!/^\d{10}$/.test(data.mobile)){setStatus("Enter a valid name, email and 10-digit mobile number.");return}try{await updateProfile(data);setEditing(false);setStatus("Profile changes saved.")}catch(error){setStatus(error.message)}}return <ProtectedRoute><Page><Breadcrumb items={[{label:"Home",href:"/"},{label:"My Account",href:"/account"},{label:"My Profile"}]}/><AccountLayout title="My Profile" description="Manage your personal information."><div className="profile-card"><div className="profile-avatar">{profile.name.charAt(0)}</div><div className="profile-fields">{[['name','Full Name'],['email','Email Address'],['mobile','Mobile Number']].map(([name,label])=><label key={name}>{label}<input disabled={!editing} value={data[name]} onChange={e=>setData({...data,[name]:e.target.value})}/>{name!=='name'&&<small>Verification status: development data only</small>}</label>)}</div><div className="profile-actions">{editing?<><button className="button button--primary" onClick={save}>Save Changes</button><button className="button button--secondary" onClick={()=>{setData(profile);setEditing(false)}}>Cancel</button></>:<button className="button button--primary" onClick={()=>setEditing(true)}>Edit Profile</button>}</div>{status&&<p className="form-status" role="status">{status}</p>}</div></AccountLayout></Page></ProtectedRoute>}
export function AddressesPage(){const{addresses,addAddress,updateAddress,removeAddress,setDefault}=useCustomer();const[editing,setEditing]=useState(null);const[adding,setAdding]=useState(false);return <ProtectedRoute><Page><Breadcrumb items={[{label:"Home",href:"/"},{label:"My Account",href:"/account"},{label:"My Addresses"}]}/><AccountLayout title="My Addresses" description="Manage delivery addresses used during checkout."><button className="button button--primary" onClick={()=>setAdding(true)}><Plus/>Add New Address</button>{adding&&<AddressForm onSave={x=>{addAddress(x);setAdding(false)}} onCancel={()=>setAdding(false)}/>}<div className="address-grid account-addresses">{addresses.map(x=>editing?.id===x.id?<AddressForm key={x.id} initial={x} onSave={data=>{updateAddress(x.id,data);setEditing(null)}} onCancel={()=>setEditing(null)}/>:<AddressCard key={x.id} address={x} onEdit={setEditing} onDelete={removeAddress} onDefault={setDefault}/>)}</div>{!addresses.length&&<p className="form-status">No saved addresses. Add one to prepare for checkout.</p>}</AccountLayout></Page></ProtectedRoute>}



